### ISSUE TITLE
How to install code as a wheel

### ISSUE THREAD

**Issue by a-recknagel** [sdispater/poetry#1002]
I'm trying to integrate poetry within my build and deploy process, and am having some difficulties with the latter.

So, build is working fine. I have code and a `pyproject.toml` file, and when I run `poetry build -f wheel` I get a wheel file, same as in my old build process. My next step would then consist of installing that wheel into a docker container, together with the dependent packages that I last tested it with. The dependency list would be the `poetry.lock` file, which I get for free, which is very nice. But I haven't seen a way to install my code as a wheel.

For illustration, this is what I imagine my dockerfile to look like:

``` bash
FROM python:3.7-alpine

COPY pyproject.toml .
COPY poetry.lock .
COPY dist/* dist/  # only wheel, no code files

RUN pip install poetry && poetry install --no-dev --no-interaction
```

The resulting container will happily install all dependencies, but not the wheel I send along.

I could of course fix it by just adding `pip install dist/*`, but it felt wrong to call pip by hand after using poetry up to now.

How do I tell poetry to install the code I'm deploying as a wheel? If that's not possible, can I use pip to install the content of the `poetry.lock` file?

**Comment by a-recknagel** [comment]
Small addendum: Just adding `pip install dist/*` doesn't solve the problem, since poetry installed the locked dependencies into a virtualenv, which I'd need to enter before running pip install. So, yeah. As expected, mixing deployment tools is no fun at all.

**Comment by mtkennerly** [comment]
Instead of manually activating the virtual environment that Poetry makes, you can do `poetry run pip install dist/*`. But I wonder if that really does what you want/think, since `poetry install --no-dev` still installs your library, so if you try this, you'll get:

```console
$ poetry run pip install dist/*.whl
Requirement already satisfied: foo==0.1.0 from file:///C:/tmp/foo/dist/foo-0.1.0 -py3-none-any.whl in c:\tmp\foo
```

...which won't actually install your wheel. For what you want, you'd probably need to do:

```dockerfile
RUN pip install poetry && \
    poetry install --no-dev --no-interaction && \
    poetry run pip uninstall -y bookie && \
    poetry run pip install dist/*
```

But that still feels kind of weird. This might not help if you have a specific reason for testing it the way you have in mind, but I think it would be more effective to split what you're doing into two tests:

* Install with Poetry and exact pinned dependencies. This ignores the wheel and tests the known good setup.
* Install the wheel with Pip and take all latest dependencies, not using Poetry. This tests the wheel and that the upper version ranges from pyproject.toml are valid.

**Comment by a-recknagel** [comment]
I'd go with this option: 
> Install with Poetry and exact pinned dependencies. This ignores the wheel and tests the known good setup.
But the problem here is that I can't find a way to isolate dependencies with poetry as something that isn't it's lockfile. I either need a way to transform poetry's lockfile into something that pip can parse, or an equivalent to `pip wheel -w put_wheel_here`, which will not only build a wheel of my source code but also of all its dependencies, in a way where I can share it between different environments.

**Comment by mtkennerly** [comment]
Gotcha. Sounds like you'd probably want the `export` command [from 1.0.0a0](https://github.com/sdispater/poetry/releases/tag/1.0.0a0) then.

**Comment by hangtwenty** [comment]
See also: #558
