### ISSUE TITLE
Installation fails due to pyobjc even when not on darwin

### ISSUE THREAD

**Issue by uyar** [sdispater/poetry#1024]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Poetry version**: 1.0.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/uyar/958326c623dbcb46c2be777f47f9e6b2

## Issue
Trying to add pywebview to the project fails when I run the command:

```
poetry add pywebview --extras qt
```
The error I get at the end of the traceback is (after a lot of pyobjc related messages):

```
[InvalidRequirement]
Invalid requirement, parse error at "'; <empty'"
```
I've also reported this to pywebview. Here's the [setup.py](https://github.com/r0x0r/pywebview/blob/master/setup.py) file for that project, and here's the [issue](https://github.com/r0x0r/pywebview/issues/326) I've posted, but it seems to me that the problem is not there. In the `install_requires` part if I replace `pyobjc` with -say- `pythonnet`, I don't get an error. Please also see [this comment](https://github.com/r0x0r/pywebview/issues/326#issuecomment-481165622) I've written there.

This issue might be related to [this poetry issue](https://github.com/sdispater/poetry/issues/978).

**Comment by uyar** [comment]
I should add that `pip install pywebview[qt]` works.

**Comment by uyar** [comment]
I'm not sure whether the underlying cause is gone or not but it seems to be OK with the new release of pywebview 3.0, so I'm closing this for now.

**Comment by gruel** [comment]
This bug is back on linux and it is linked to the package keyboard. It can be tested with:

`[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "test"
version = "0.1"
description = ""
authors = [ "",]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
keyboard = "^0.13"`

doing a:

`poetry install`

to create the poetry.lock will show that poetry is adding a dependency on pyobjct even on linux:

` [[package]]
category = "main"
description = "Hook and simulate keyboard events on Windows and Linux"
name = "keyboard"
optional = false
python-versions = "*"
version = "0.13.5"

[package.dependencies]
pyobjc = "*"

[[package]]
category = "main"
description = "Python<->ObjC Interoperability Module"
marker = "sys_platform == \"darwin\""
name = "pyobjc"
optional = false
python-versions = ">=3.6"
version = "6.2"
...`
