### ISSUE TITLE
Issues with python-versions

### ISSUE THREAD

**Issue by Tonkonozhenko** [sdispater/poetry#104]
When I'm trying to add package with python version specific requirements, I do not see them in pyptoject.lock

```
(.venv) ➜ poetry add traitlets
Using version ^4.3 for traitlets

Updating dependencies
Resolving dependencies..


Package operations: 2 installs, 1 update, 0 removals

Writing lock file

  - Updating decorator (4.0.11 -> 4.3.0)
  - Installing ipython-genutils (0.2.0)
  - Installing traitlets (4.3.2)

```

pyproject.lock:
```
...
[[package]]
category = "main"
platform = "UNKNOWN"
version = "1.1.6"
name = "enum34"
python-versions = "*"  # ???
optional = false
description = "Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4"
...
```

**Comment by sdispater** [comment]
This is definitely a bug.

I will look into it and get back to you.

**Comment by sdispater** [comment]
Well, there is actually a bug in how poetry retrieve the python requirements from packages that needs to be downloaded but even if I fix it it won't change anything in the case of enum34 since this information is not available anywhere so poetry will still consider any python version is possible.

However, if you meant that traitlets only require enum34 for python < 3.4 then this appears in the `requirements` property in the lock file.

```toml
[[package]]
name = "enum34"
version = "1.1.6"
description = "Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4"
category = "main"
optional = false
python-versions = "*"
platform = "UNKNOWN"

[package.requirements]
python = "~2.7"
```

**Comment by sdispater** [comment]
Release `0.10.0` is out and should fix the issue of missing python versions with compliant packages.
