### ISSUE TITLE
Poetry does not parse constraint containing double quotes

### ISSUE THREAD

**Issue by nicolas-leydet** [sdispater/poetry#1278]
- **OS version and name**: openSUSE Leap 15.0
- **Poetry version**: 0.12.17

## Issue
`poetry add redislite` returns

```
[ValueError]                    
Could not parse version constraint: >="2.7" 
```

The package is installed correctly if pip is used

It is coming from the parsing of the python version (redislite package use double quotes for this constraint). I understand that this use of double quote might not be standard.

**Comment by brycedrennan** [comment]
Perhaps we could make the poetry parser more forgiving but I'd suggest opening a pull request with redislite.

**Comment by jrabbit** [comment]
Same issue w/ https://github.com/pytest-dev/pluggy/blob/master/setup.py#L40 this breaks all my tox-enabled projects and limits my ability to set a real python compat `~2.7 || ^3.5`

**Comment by sdispater** [comment]
@jrabbit This is not the same thing. The initial issue is with the `python_requires` property while what you are pointing at is environment markers which can be parsed properly since I never add any issue with pluggy.

@nicolas-leydet The issue is on redislite's end since quotes are not supported in the `python_requires` field as far as I know: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
