### ISSUE TITLE
dynamic version

### ISSUE THREAD

**Issue by dpgaspar** [sdispater/poetry#1314]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
I'm migrating a project to poetry

I would like to make the `version` based on the contents of a file, say JSON or `__init__.py` any advice you can offer?

**Comment by finswimmer** [comment]
I'm looking for the exact same thing.

The reason for this is, that I need the version number within my package as well.

**Comment by finswimmer** [comment]
Another way I could think of, is that there is in option for `poetry version` to write the bumped version to a `__version__.py` as well. Because this is a place where lots of people store their package version number as well. (poetry as well ;) )

**Comment by dmontagu** [comment]
I have been using (and loving) the trick from this comment: https://github.com/sdispater/poetry/issues/144#issuecomment-485287982

In order to adapt it to your own project, all you need to do is change `x12_utils/__init__.py` to the path to whatever file you want to contain your project's version number.

Then you can run that make command (or shell script, if you use that approach) to have `poetry` set the version in `pyproject.toml`, and have `sed` set the version (output by poetry) in the version file.

The only restriction is that the same version string shouldn't show up in an unrelated way in the file (e.g., don't run it on a file that includes version numbers for all of your dependencies).

**Comment by finswimmer** [comment]
Thanks for pointing me to that issue!

Having a custom script that do the version bumping in all files is one workaround but would introduce a new "tool" beside poetry. But I like other solutions mentioned there and in linked issues:

- [using pkg_resources](https://github.com/sdispater/poetry/issues/144#issuecomment-393257700)
- [using importlib_metadata](https://github.com/sdispater/poetry/issues/1036#issuecomment-489880822)

With the last one, one can get all metadata shipped with the package and is intended to get integrated in python3.8 (before one has to install it via pip)
