### ISSUE TITLE
Cython Extensions

### ISSUE THREAD

**Issue by frnkvieira** [sdispater/poetry#137]
Hello! Firstly, this project is awesome.

I'm a heavy user of C extensions and Cython modules but they are specified in the setup.py file to be compiled to native code at install time. I'm not sure if they should be specified in "pyproject.toml" because even in the PEP there are no mentions to it. I'm willing to do a pull request if needed so I just need a direction :)

Keep the great work, many thanks!

**Comment by ethanhs** [comment]
AIUI, this would requite Cython to create a build backend as specified in https://www.python.org/dev/peps/pep-0517. Then poetry would "just" need to add support for PEP 517.

**Comment by ethanhs** [comment]
It seems like currently you can use the undocumented (unstable) build.py like in #11.

**Comment by salotz** [comment]
I added an example on using cython in #11. Cython probably wouldn't have to have the build backend (except as a library which it basically already has in the form of `cythonize`). From how I understand PEP 517 only one build backend is [allowed anyhow](https://www.python.org/dev/peps/pep-0517/#source-trees) since the 'build-backend' is just a single string and Cython would never be the only build backend. So `poetry`, `flit`, or ([more likely](https://github.com/pypa/pip/issues/5407)) `pip` will be the build backend. That is unless poetry takes the place of pip. For instance if you try to install that package I made with `pip` from source you need to have `Cython` already installed without the PEP 518 `requires = ['setuptools', 'wheel' 'Cython']` which pip supports now and installs cython before building.

**Comment by salotz** [comment]
So this issue can be closed if poetry can be used as a build backend. How that is implemented (`build.py` etc.) is another issue probably.

**Comment by stephsamson** [comment]
Closing this issue, see solutions (by [@sdispater](https://github.com/sdispater/poetry/issues/11) and [@salotz](https://github.com/sdispater/poetry/issues/11#issuecomment-429083234) in #11).
