### ISSUE TITLE
Error message when version doesn't update pyproject.toml

### ISSUE THREAD

**Issue by nathan5280** [sdispater/poetry#1388]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I just got started with Poetry today and added a private repository "[[tool.poetry.source]]" to the pyproject.toml file.  I didn't really think about it and added it right to the top of the file.  When I run "poetry version" it reports that it is updating the version, "Bumping version from 0.4.2-alpha.0 to 0.4.2", but it doesn't update the file.

Request:
1) If it is truly invalid to put this section at the top then an error should be reported.
2) If it is valid to put this section at the top and for some reason Poetry has some other problem updating the version and writing the file it would be good to fix this.

**Comment by etijskens** [comment]
I had similar problem caused by the order of entries in the pyproject.toml file which went without being reported as an error in poetry.
see issue https://github.com/sdispater/poetry/issues/1182

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 19 Sep 2019, at 00:27, Nathan Atkins <notifications@github.com<mailto:notifications@github.com>> wrote:


  *    I have searched the issues<https://github.com/sdispater/poetry/issues> of this repo and believe that this is not a duplicate.
  *    I have searched the documentation<https://poetry.eustace.io/docs/> and believe that my question is not covered.

Feature Request

I just got started with Poetry today and added a private repository "[[tool.poetry.source]]" to the pyproject.toml file. I didn't really think about it and added it right to the top of the file. When I run "poetry version" it reports that it is updating the version, "Bumping version from 0.4.2-alpha.0 to 0.4.2", but it doesn't update the file.

Request:

  1.  If it is truly invalid to put this section at the top then an error should be reported.
  2.  If it is valid to put this section at the top and for some reason Poetry has some other problem updating the version and writing the file it would be good to fix this.

**Comment by nathan5280** [comment]
Well I feel good that I only spent  hours on this.  I'll close this issue and point to #1182.

This issue seems to fit a number of related issues where the order of the entries in the pyproject.toml impact whether or not the file is updated by "poetry version".  See Issue [#1182](https://github.com/sdispater/poetry/issues/1182).

**Comment by etijskens** [comment]
That makes me feel good that after several days of debugging I was able to pin down the problem and that I posted this :)
This is a very counterintuitive bug

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 19 Sep 2019, at 15:08, Nathan Atkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Well I feel good that I only spent hours on this. I'll close this issue and point to #1182<https://github.com/sdispater/poetry/issues/1182>.

This issue seems to fit a number of related issues where the order of the entries in the pyproject.toml impact whether or not the file is updated by "poetry version". See Issue #1182<https://github.com/sdispater/poetry/issues/1182>.
