### ISSUE TITLE
Output only the version number with `poetry version`

### ISSUE THREAD

**Issue by wesleykendall** [sdispater/poetry#1407]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Running `poetry version` outputs something to the nature of `Project (<name>) version is 0.1.0`. There seems to be no way to only obtain the version (i.e. 0.1.0), which is what I personally expect `poetry version` to output. It makes it a little bit more cumbersome to do automated version updates in continuous delivery server (e.g. get the current version number after a version update so that a repo can be tagged).

I would like to suggest either:

1. `poetry version --number` (or another acceptable option name since not everyone uses numbers for versions) outputs only the version and not the project information
2. `poetry version` outputs only the version number and `poetry version -l` prints out the more descriptive version information.
3. Updating the FAQ with an example of how to get the version number by parsing stdout (along with an associated unit test). I'd feel more confident implementing a solution around parsing stdout if we can rely on the stdout not changing.

I'm happy to implement this solution however the maintainers see fit if the community believes it would make automated scripts around the package version easier. And I'm also open to writing an extension/plugin if poetry supports that.

**Comment by etijskens** [comment]
You can easily read it from pyproject.toml:
    project_path = Path(project_path)
    pyproject_toml = toml.load(str(project_path /'pyproject.toml'))
    print( pyproject_toml['tool']['poetry']['version’] )

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 24 Sep 2019, at 23:43, Wes Kendall <notifications@github.com<mailto:notifications@github.com>> wrote:


  *    I have searched the issues<https://github.com/sdispater/poetry/issues> of this repo and believe that this is not a duplicate.
  *    I have searched the documentation<https://poetry.eustace.io/docs/> and believe that my question is not covered.

Feature Request

Running poetry version outputs something to the nature of Project (<name>) version is 0.1.0. There seems to be no way to only obtain the version (i.e. 0.1.0), which is what I personally expect poetry version to output. It makes it a little bit more cumbersome to do automated version updates in continuous delivery server (e.g. get the current version number after a version update so that a repo can be tagged).

I would like to suggest either:

  1.  poetry version --number (or another acceptable option name since not everyone uses numbers for versions) outputs only the version and not the project information
  2.  poetry version outputs only the version number and poetry version -l prints out the more descriptive version information.
  3.  Updating the FAQ with an example of how to get the version number by parsing stdout (along with an associated unit test). I'd feel more confident implementing a solution around parsing stdout if we can rely on the stdout not changing.

I'm happy to implement this solution however the maintainers see fit if the community believes it would make automated scripts around the package version easier. And I'm also open to writing an extension/plugin if poetry supports that.

**Comment by wesleykendall** [comment]
@etijskens sure, one can do this in Python, but hardcoding the project path, including a separate python script in your repo just to print a version, and also ensuring that a toml parser is installed is not a simple solution at all. Especially if you are scripting a pipeline for continuous delivery and publishing of many different python projects.

Poetry's main use case is for packaging and publishing, which as a result means that the version number is needed for many other things related to publishing the library (tagging the repo, adding the version string to the automated docs, etc). 

For example, a script to do an automated version bump might look like:

```
latest_tag = `git describe --abbrev=0 --tags`
# Set the version to the latest tag
poetry version latest_tag
# Patch the version
poetry version patch
# Get the new version and tag the repo
new_version = `poetry version | some regex parsing to parse output`
git tag new_version
...
```

In order to get the current version of the repo, I have to parse the output of `poetry version`, which is a sentence of text and not some sort of delimited structured text (like an `ls -l` for example). It is strange that I can do complex semantic versioning commands to update the version (e.g. `poetry version major`), but I can't do something as simple as get the version after it is updated without resorting to parsing text.

Again, I appreciate the suggested solution in Python, but the purpose of this was to suggest it as a feature since getting the package version is a core aspect of publishing python projects. If the maintainers are happy with any of my suggested approaches, I'm more than happy to open a PR

**Comment by funkyfuture** [comment]
> If you think it is still relevant and should be addressed, feel free to open a new one.

@stale could you just reopen this one, please?

**Comment by finswimmer** [comment]
Hello @funkyfuture ,

since version 1.0.0b6 the output of `poety version` has changed to a more simple format (https://github.com/sdispater/poetry/pull/1591), that can be easily parsed. Are you fine with this?

fin swimmer

**Comment by muppetjones** [comment]
> Hello @funkyfuture ,
> 
> since version 1.0.0b6 the output of `poety version` has changed to a more simple format (#1591), that can be easily parsed. Are you fine with this?
> 
> fin swimmer

It's better. It would still be nice to have an option to just print the version.

**Comment by michaelgoldendev** [comment]
It turns out this is now possible (although it doesn't appear to be documented):
```
poetry version -s
```

**Comment by mkniewallner** [comment]
> It turns out this is now possible (although it doesn't appear to be documented):

It is documented, both on [1.1 documentation](https://python-poetry.org/docs/cli/#options-10) and on [master one](https://python-poetry.org/docs/master/cli/#options-11).
Same for the CLI itself:
```console
$ poetry version --help | grep "short"
  -s, --short           Output the version number only
```
