### ISSUE TITLE
Can't add github repository - version solving failed.

### ISSUE THREAD

**Issue by p-baum** [sdispater/poetry#1474]
I just split out some code into its own repo and want to add it back in as a dependency like so:

`poetry add jsonrpc-utils --git https://github.com/p-baum/jsonrpc-utils.git`

but i get the following error:

`Because myproj depends on jsonrpc-utils (*) which doesn't exist, version solving failed.`

What is wrong?

**Comment by sdispater** [comment]
Please, next time you report an issue, fill in the appropriate issue template so we can have the necessary information to debug and reproduce issues.

As for the root cause for what you are experiencing is that https://github.com/p-baum/jsonrpc-utils is not a valid Python package. you are missing either a `pyproject.toml` file with a `too.poetry` section or a `setup.py/setup.cfg` file.

**Comment by p-baum** [comment]
Ok. Thankyou
