### ISSUE TITLE
Problem with dependency resolution with django and django-static-precompiler

### ISSUE THREAD

**Issue by oliverandrich** [sdispater/poetry#1551]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina
- **Poetry version**: 1.0.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/oliverandrich/dc43195c59b934b0e276fdeff2c62c3b

## Issue
When I execute the following command I get an error message that suggests that poetry somehow thinks it has to use the [setup.py](https://github.com/andreyfedoseev/django-static-precompiler/blob/master/setup.py) code for Python 2 from djangp-static-precompiler. 

```
❯ poetry add "django-static-precompiler[libsass]" django
Using version ^1.8.2 for django-static-precompiler
Using version ^2.2.7 for django

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
Because django-static-precompiler (1.8.2) depends on Django (>=1.7,<2.0)
 and no versions of django-static-precompiler match >1.8.2,<2.0.0, django-static-precompiler (>=1.8.2,<2.0.0) requires Django (>=1.7,<2.0).
So, because django-project-boilerplate depends on both django-static-precompiler (^1.8.2) and django (^2.2.7), version solving failed.
```

Here is the code, that might cause the trouble. 

```
if sys.version_info.major == 2:
    install_requires = [
        "Django>=1.7,<2.0",
    ]
elif sys.version_info.major == 3:
    install_requires = [
        "Django>=1.9",
    ]
else:
    raise AssertionError()

if sys.version_info < (3, 5):
    install_requires += [
        "typing",
    ]
```

Is it possible, that poetry somehow executes the setup.py with the system wide installed Python 2?

**Comment by sdispater** [comment]
Poetry does not execute the `setup.py` file when resolving dependencies for security reasons.

However, in this particular case it uses the `requires.txt` file which looks like this:

```
Django<2.0,>=1.7
typing

[libsass]
libsass

[watch]
watchdog
```

So Poetry only sees the `Django<2.0,>=1.7` constraint.

The issue lies with their `setup.py`, as you pointed out, which should not specify dependencies programmatically but declaratively by using [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers).

This should be reported upstream.

Closing since it's not an issue with Poetry.
