### ISSUE TITLE
Exclude is not respected when building package.

### ISSUE THREAD

**Issue by mhozza** [sdispater/poetry#1597]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux 5.3.11-arch1-1
- **Poetry version**: 1.0.0b5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/mhozza/345f427c76880295fe5c8b3d630925d6
## Issue

Exclude is not respected when building package.

I have `**/node_modules/**` in my `.gitignore` and I also included `exclude = ["**/node_modules"]` in my pyproject.toml file, but none of them causes the _node_modules_ to be ignored.

When I do `poetry build -vvv` I see a lot of lines similar to:
```
 - Adding: /home/mio/source/trojstenweb/trojsten/special/plugin_prask_2_4_1/static/plugin_prask_2_4_1/js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-runtime/node_modules/core-js/fn/log.js
```

**Comment by finswimmer** [comment]
Hello,

this is already fixed by https://github.com/sdispater/poetry/pull/1464 but obviously it is not included in the current version

Can you please check the output of `git ls-files --others -i --exclude-standard`? Because I would thought that the `.gitgnore` should work. If the files you want to excluded that you have already added them with `git add`. You will have to remove them from the git tracking. 

Nevertheless with the fix already in dev the `pyproject.toml` should work.

@sdispater Is this correct that the fix isn't in the current release?

**Comment by mhozza** [comment]
Thanks for the response.

`git ls-files --others -i --exclude-standard` contains these files. I'm quite sure they are not commited to the repository or added using `git add`.
`exclude = ["**/node_modules/**/*"]` makes no difference, so I'm not sure if the fix will actually help. I'm wondering if recursive glob should be used.

Not sure if relevant, but I also have

```toml
packages = [
  { include = "trojsten"}
]
```
in my pyproject.toml file.

**Comment by finswimmer** [comment]
I had the time to take a closer look at this:

* In any case have the `.gitignore` version works for me
* `exclude = ["**/node_modules/**/*"]` works
* `exclude = ["**/node_modules/"]` doesn't work, even with linked fix

So I will work on a fix for the last point.
