### ISSUE TITLE
Register entry point hooks for things like pytest/click etc.

### ISSUE THREAD

**Issue by EdgyEdgemond** [sdispater/poetry#1641]
- [x ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
I don't know if I am missing the documentation (wouldn't be my first time)

I have found the details on how to create entry_points.console_script. I'm now looking to tie into other entry points hooks (specifically pytest this time).

I am looking for the poetry equivalent of the following setup.py code.
```
    entry_points={
        "pytest11": [
            "cool_plugin = pytest_cool_plugin",
        ],
    },
```

If I am just missing something please direct me to the docs, or if this is a dupe to the tracked issue so I can follow it.

**Comment by pawamoy** [comment]
Based on the documentation, I think you can do it like this:

```toml
[tool.poetry.plugins.pytest11]
cool_plugin = "pytest_cool_plugin"
```

Related: #1300 and #1454 (poetry to support setuptools-like "plugins" entry-points), #693 (poetry to support plugins for itself), #658 (documentation on the difference between the two). I don't know why the first two issues are not closed since plugins entry-points seem to be implemented.

**Comment by EdgyEdgemond** [comment]
ah cheers, I'll give that a shot

**Comment by EdgyEdgemond** [comment]
My plugin works as expected. Thanks for the guidance.
