### ISSUE TITLE
poetry version does not update __version__ in __init__.py

### ISSUE THREAD

**Issue by tsiq-rob** [sdispater/poetry#1652]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14
- **Poetry version**: 1.0.0b8

## Issue

`poetry new` creates an `__init__.py` containing `__version__ = '0.1.0'`
`poetry version {version}` does not update `__init__.py`

Either `poetry new` should not create this constant, or `poetry version` should modify it.

**Comment by finswimmer** [comment]
Hello @tsiq-rob ,

this is already discussed in #144.

fin swimmer

**Comment by tsiq-rob** [comment]
thank you, I missed it in the torrent of bug reports :)

**Comment by pawamoy** [comment]
Oh well, I didn't know poetry was writing `__version__` in `__init__.py`. Maybe it should indeed stop doing that :confused:

**Comment by lnxpy** [comment]
### For those who want to access `__version__` in a poetry-managed Python package..

I used to work with `bumpversion` and that was fine reading `__version__` from `__init__.py` and with my defined searching patterns, it would simply find the versions and bump them quite cleverly.

Since poetry has already removed the metadata information from `__init__.py`, a quick way to access the version of the package (maybe for implementing the `--version` option) would be to use the following trick.

```python
# your-package/your-package/main.py
import importlib.metadata

__version__ = importlib.metadata.version('your-package')
```

This way, your `__init__.py` will be kept empty as well, but keep in mind, your package must be installed in the `site-packages` either via `pip` or `poetry`. It takes the version from there.
