### ISSUE TITLE
How to choose venv name or rename it?

### ISSUE THREAD

**Issue by nicolashainaux** [sdispater/poetry#263]
Hello,

Thanks for this great software!

I'm currently trying it with a new project and see the virtual environment's name is set to 'project-name.py3.6' (for python 3.6 projects) and I would like to rename it.

I have actually changed the venv's directory's name. It shows up correctly in the prompt, and `poetry show -v` seems to take it into account correctly. Also, I have changed all the occurrences of the default name in the virtual environment scripts. Is it enough? Could there be some side effects I cannot detect now, that could turn out problematic later?

Alternatively, I guess that could be nice to be able to choose the venv name directly when creating a new project.

**Comment by jeremy886** [comment]
According to the docs: poetry will also detect if you are inside a virtualenv and install the packages accordingly. So, poetry can be installed globally and used everywhere.

My approach is using an virtual environment wrapper like pew to choose whatever name I want. https://github.com/berdario/pew

**Comment by nicolashainaux** [comment]
OK, for some reason I thought `poetry`  had to run outside the virtual environment (while doing everything inside it).

So, good, it's possible to create the venv via `python -m venv name`, `source path/to/venv/bin/activate` and then run `poetry add a_package`. Fine, this closes the issue I think! Thanks a lot!

**Comment by multitasked** [comment]
There is still one option. Set the settings `poetry config virtualenvs.in-project true` so that the virtual environment is installed in the project folder. then the name of the virtual environment will be (. venv)

**Comment by Zaffer** [comment]
Please reopen this as the title of the issue has not been resolved from the solutions here. How do I rename the virtual environment the poetry sets up with "packagename-TotAllY2LongSlug-py3.8". I would like just name exactly please?

**Comment by Zaffer** [comment]
Please reopen, as this make Poetry useless for share repo with a team needing to create their own shells.

**Comment by timoguin** [comment]
I'm working to optimize a development setup with multi-stage Docker builds. Not being able to know the name of the virtualenv that is created by Poetry is making things tricky. I know about using `.venv` directly in the project, but, with my specific use-case, there are some difficulties associated with that (pre-installing deps and then needing to bind mount the source from the host).

It would be great if I could just give the virtualenv a name or otherwise know the explicit path.

**Comment by clintonroy** [comment]
As has been mentioned multiple times, you can create a virtual environment, using any name you want, activate it, and poetry will use it. 

I'm yet to see any work flow that would be enhanced by adding yet another option to poetry to specify the virtual env name.

In docker, adding the venv's bin path to the head of PATH activates the venv.

**Comment by odigity** [comment]
I found this thread while trying to answer these two questions:

1. How does Poetry choose the virtualenv name to create?
2. How does Poetry know which one you desire when running `poetry shell`?

It's a mystery to me because I couldn't find any mention of this in the docs, and I don't see any obvious state files storing the association - not in the project dir, or `~/.config/pypoetry`, or `~/.cache/pypoetry`.

**Comment by neersighted** [comment]
`poetry env info --path` is provided in the docs as a way to get the environment path. Poetry's environment management is intentionally opaque/minimal as it's not a problem space the project wants to tackle -- we can support existing workflows/tools instead of emulating them poorly.

Likewise, support for `virtualenvs.in-project` is well documented. If you see some specific shortcomings in the virtualenv docs, please do open a PR.

**Comment by timoguin** [comment]
I dove into the code a month ago after my last exchange and found that the generated ID at the end of the venv name is a hash computed mostly from the project's absolute path.

That logic needs to be surfaced. It's great that we can create our own venv and tell Poetry to use it, but we should also be able to do the reverse.

I came here after I was building a certain Docker setup where I was trying to use `poetry install` from a `/tmp` dir, and then trying to use that same venv at a later stage from a non-temp directory. But I didn't have an easy way to know how the generated venv was going to be named.

The options for us in these use cases feel a bit hacky to me.

**Comment by neersighted** [comment]
Right, that's what I meant by "intentionally opaque" -- we hash the path as otherwise two projects with the same name (even two git worktrees or clones) will overwrite each others environment. That's not something that is likely to change, it's specifically because of lessons learned from other tools.

If you are trying to control the virtual environment path in a Dockerfile, the canonical method is:

```dockerfile
RUN python -m venv /path/to/app/venv
ENV PATH="/path/to/app/venv/bin:$PATH" VIRTUAL_ENV=/path/to/app/venv
RUN poetry install
```

Setting `PATH` and `VIRTUAL_ENV` has the effect of activating the virtual environment and causing all following `RUN` lines to use that environment; all your `poetry` and `python` commands will 'just work.'

**Comment by timoguin** [comment]
@neersighted Thanks for your clarifications! I posted my last replay at almost the same time as yours, so I hadn't seen your response.

🙏
