### ISSUE TITLE
How to get version from pyproject.toml from python app?

### ISSUE THREAD

**Issue by sobolevn** [sdispater/poetry#273]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I have a basic python app, and inside this app there's a `--version` flag.
I want to show the same version as I have in `pyproject.toml`, but without duplicating this information.

What should I do here?
Thanks!

**Comment by roywes** [comment]
The `pkg_resources` module enables package information introspection. Here's how it can be used to get the version of an installed package.

```py
>>> import pkg_resources
>>> my_version = pkg_resources.get_distribution('my-package-name').version
```

**Comment by piotr-dobrogost** [comment]
Related: [Single-sourcing the package version](https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-package-version) from Python Packaging User Guide

**Comment by sobolevn** [comment]
Thanks. I am using https://github.com/sdispater/poetry/issues/273#issuecomment-401983643

**Comment by nchammas** [comment]
Using `pkg_resources.get_distribution()` implies a dependency [on setuptools](https://setuptools.readthedocs.io/en/latest/pkg_resources.html), no? I think one of the goals of Poetry is to eliminate the need for setuptools.

For what it's worth, I see that Poetry itself simply [duplicates](https://github.com/sdispater/poetry/blob/0.11.4/poetry/__version__.py) the [version](https://github.com/sdispater/poetry/blob/0.11.4/pyproject.toml#L3).

I think there currently isn't a "proper" solution for single-sourcing the application version in a project packaged by Poetry.

**Comment by timonbimon** [comment]
any update on how to do this best? does following how Poetry does it itself really mean updating the __version__.py file by hand?

**Comment by sobolevn** [comment]
I am using @roywes solution with a fallback to 
https://github.com/wemake-services/wemake-python-styleguide/blob/master/docs/conf.py#L22-L37

when the package is not installed.

**Comment by Eric-Arellano** [comment]
You can now use `importlib.metadata` and its backport `importlib_metadata`: https://docs.python.org/3/library/importlib.metadata.html#distribution-versions.

It has a convenient function `importlib.metadata.version('my-distribution')` that will return a `str` read from your `pyproject.toml` configuration.

**Comment by insysion** [comment]
Just for clarity, `importlib.metadata` isn't reading directly from the `pyproject.toml` is it?

The docs seem to say that a package *built by poetry* and *installed* will have the metadata version set _from_ the `pyproject.toml` field

**Comment by ErikBjare** [comment]
@insysion The metadata is built from the pyproject.toml (into these locations in the sdist: `setup.py`, `pyproject.toml`, `PKG-INFO`), but the `importlib.metadata` probably gets it from the version set in the poetry-built `setup.py`.

**Comment by cglacet** [comment]
It seems both `pkg_resources.get_distribution('my-package-name').version` and `importlib.metadata.version('my-package-name')` needs the package to be installed which seems odd when you are building the doc for that particular package (from local sources). Is there a way to instead simply get the version that is currently built?

**Comment by sinoroc** [comment]
@cglacet You could directly parse the TOML in `pyproject.toml`.
What is the context exactly? Why can't you install or at least build the project?

**Comment by cglacet** [comment]
@sinoroc Yes I could, but isn't including a package as its own dependency weird?

**Comment by sinoroc** [comment]
> isn't including a package as its own dependency weird?

I am not following.

**Comment by cglacet** [comment]
@sinoroc That's probably not clear because it's not clear in my head haha. If I need to load a package to get its version, then, to get the current version of the package I'm currently building it needs to install itself (so it can read its own version number). In my case, I want to include the version number in the package documentation (sphinx configuration).

And I also want that particular piece of code to run even while in development (because I will build the documentation locally a lot before its built by my CI pipeline)

**Comment by cglacet** [comment]
Like you said, I could very well parse the `pyproject.toml` file, but I'm surprised my use case doesn't already have a solution. I'm not trying to do anything fancy 😄

**Comment by sinoroc** [comment]
> I'm surprised my use case doesn't already have a solution

I know that it is a question that keeps coming up again and again, and there is still no one true answer. It all depends on what the context and conditions are. There are multiple solutions, all with their pros and cons.

---

Since you mention building sphinx documentation I will tell here how it is solved in one of my projects...

The `conf.py` for sphinx contains something like:

```
import importlib.metadata

_DISTRIBUTION_METADATA = importlib.metadata.metadata('MyProjectName')

author = _DISTRIBUTION_METADATA['Author']
project = _DISTRIBUTION_METADATA['Name']
version = _DISTRIBUTION_METADATA['Version']
```

and the `readthedocs.yml` file contains something like:

```
version: 2
python:
  install:
    - method: 'pip'
      path: '.'
```

So, yes it means that the project always has to be installed beforehand (at least in _editable_ (aka _develop_) mode). It is a bit of a shame, I reckon, but it works well, so I leave it like that for now.

Although I believe it would be relatively easy, to extract the version string (and other metadata) from a _build_ artefact of the project, instead of from a complete installation.

---

In the case of poetry projects, since the source of truth for the version string is in `pyproject.toml` file:
Instead, in _Sphinx_'s `conf.py` you could import a _toml_ parser and extract the metadata (version string, etc.) out of `pyproject.toml`. It would avoid building and installing the project itself.

---

> If I need to install a package to get its version, then, to get the current version of the package I'm currently building it needs to install itself (so it can read its own version number)

This bit, I do not understand what you mean. Where is the issue? Usually libraries or applications do not really need to know their own version string. And if they do have this need, then I would definitely think that it is at run-time, meaning that they are already installed. So using `version = importlib.metadata.version('MyProjectName')` should be straightforward, right?

**Comment by andschwa** [comment]
Wow, thank you @sinoroc. Your example helped me immensely.

**Comment by abolourian** [comment]
I'm looking for a solution to run in `poetry-script.py` and the solutions above doesn't work. This worked for me though.
`subprocess.run(['poetry', 'version', '-s'], capture_output=True, text=True).stdout.rstrip()`

**Comment by sinoroc** [comment]
@abolourian What are you trying to do? How is your use case different than others' use cases? What is the `poetry_script.py` you are talking about? What have you tried exactly that didn't work for you?

**Comment by abolourian** [comment]
@sinoroc In a CICD process, I'm using a method in `poetry_script.py` to (1) bump the `[tool.poetry].version` in `pyproject.toml` file, (2) extract the version and write it to `_version.py` file, and (3) create zip files for AWS Lambda packages. I need the statement I mentioned in my previous comment for step 2.

**Comment by sinoroc** [comment]
@abolourian

Basically everything I am saying is: don't write a `_version.py`, and don't write your version string in `__version__` of your main top level package's `__init__.py` either, or anything like that. There is no need for that. My recommendation is to call `importlib.metadata.version('LibraryName')` at run-time instead.

If really you want to do it, fair enough, no problem. You approach with calling `poetry version --short` in a subprocess seems good enough. My personal opinion is that I don't think it's a good practice, and I also believe the default project skeleton created by `poetry new` should not have this `__version__` string. If I remember right some of the maintainers also think it might be time to get rid of this.

Also I would like to mention the project [_`poetry-scmver`_](https://pypi.org/project/poetry-scmver/). I don't recommend it, but it exists and it seems to work.

You might also want to read this thread: https://github.com/python-poetry/poetry/issues/693

And take note that there is a project of a [real plugin system in poetry](https://github.com/python-poetry/poetry/pull/1237), scheduled for [_v1.2_](https://github.com/python-poetry/poetry/projects/6). Which might allow to do such things in a much cleaner fashion.

Other discussion on the topic: https://github.com/python/importlib_metadata/issues/248

**Comment by rabbit72** [comment]
I was surprised that there is no approach of how to keep the version of a project in one place, without duplication.
I've created a pretty simple library which allows me to have a single source.
https://github.com/rabbit72/single-source

**Comment by adriaromero** [comment]
In case anyone needs to get the version in bash, this is your command:

```
poetry version | awk 'END {print $NF}'
```

And for the shortened version:

```
poetry version | awk 'END {print $NF}' | sed -e 's/-alpha./a/' -e 's/-beta./b/'
```

**Comment by chmouel** [comment]
or shorter version :

```bash
POETRY_NAME_VERSION="$(poetry version)"
PACKAGE_NAME=${POETRY_NAME_VERSION% *}
VERSION=${POETRY_NAME_VERSION#* }
```

**Comment by ricardogaspar2** [comment]
> or shorter version :
> 
> ```shell
> POETRY_NAME_VERSION="$(poetry version)"
> PACKAGE_NAME=${POETRY_NAME_VERSION% *}
> VERSION=${POETRY_NAME_VERSION#* }
> ```

now one can use `poetry version --short` see: https://python-poetry.org/docs/cli/#version

**Comment by adam-grant-hendry** [comment]
> The docs seem to say that a package built by poetry and installed will have the metadata version set from the pyproject.toml field

@insysion 

You are right, no, it is not read from `pyproject.toml`. From [the python docs](https://docs.python.org/3/library/importlib.metadata.html)

> Specifically, it means a package with either a discoverable dist-info or egg-info directory, and metadata defined by [PEP 566](https://www.python.org/dev/peps/pep-0566) or its older specifications.

[PEP 241](https://www.python.org/dev/peps/pep-0241/#version) was the predecessor to PEP 566 that first defined the `Version` field in the `.dist-info/` file `PKG-INFO`. Metadata is read from here.

@ErikBjare 

It is _built_ from `version` specified in the `pyproject.toml` using whichever `build-backend` is specified, but it is _read_ from the `.dist-info/PGK-INFO` file created in `Lib/site-packages` when the package is installed.

**Comment by maresb** [comment]
To effectively single-source the version number (more precisely to read the metadata of the installed or editable-installed package, which originates from `pyproject.toml`), the following works well for me.

#### Simple solution for Python ≥3.8

For Python ≥3.8 in my `__init__.py` I do:

```python
from importlib import metadata

__version__ = metadata.version(__package__)

del metadata  # optional, avoids polluting the results of dir(__package__)
```

and then I import the `__version__` variable wherever I need it. For instance, if I'm at the top-level of my package:

```python
from . import __version__
```

In case you're incorrectly using your Python package then the above will fail both since `__package__` will be undefined and relative imports won't work. (For instance it fails if you try to execute your package as a script with `python main.py` instead of as a module with `python -m my_package.main`.) But the solution here is to use your package!

#### Python ≤3.7

In case you need to support lower versions of Python it's a bit more complicated... you can add the dependency on the backport
```toml
importlib-metadata = {version = ">=1.7.0", python = "<3.8"}
```

and then do something like

```python
import sys

if sys.version_info[:2] >= (3, 8):
    from importlib import metadata
else:
    import importlib_metadata as metadata

__version__ = metadata.version(__package__)

del metadata, sys  # optional
```

**Comment by koffie** [comment]
> For what it's worth, I see that Poetry itself simply [duplicates](https://github.com/sdispater/poetry/blob/0.11.4/poetry/__version__.py) the [version](https://github.com/sdispater/poetry/blob/0.11.4/pyproject.toml#L3).
> 

Apparently this is no longer the case starting from `version = "1.2.0-beta.1"` see: https://github.com/python-poetry/poetry/commit/dca6ff2699a06c0217ed6d5a278fa3146e4136ff

**Comment by maresb** [comment]
Hmm, Poetry's new way of declaring the version in the latest beta seems very strange to me. It violates the ["quasi-standard" convention](https://stackoverflow.com/a/459185) of defining the `__version__` variable in the package's top-level `__init__.py`.

```python
import poetry
poetry.__version__  # AttributeError
import poetry.__version__
poetry.__version__.__version__  # '1.2.0b1'
```

Does anyone understand the logic here? Am I missing something? (Should this be reported?)

**Comment by miron** [comment]
@maresb 

`__init__.py` is standard for regular packages (up to Python 3.2), but not for namespace packages:

https://docs.python.org/3/reference/import.html#regular-packages

https://peps.python.org/pep-0420/

**Comment by epogrebnyak** [comment]
> In case anyone needs to get the version in bash, this is your command:
> 
> ```
> poetry version | awk 'END {print $NF}'
> ```
> 
> And for the shortened version:
> 
> ```
> poetry version | awk 'END {print $NF}' | sed -e 's/-alpha./a/' -e 's/-beta./b/'
> ```

why not `poetry version -s`?

**Comment by arl-lakera** [comment]
> > In case anyone needs to get the version in bash, this is your command:
> > ```
> > poetry version | awk 'END {print $NF}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And for the shortened version:
> > ```
> > poetry version | awk 'END {print $NF}' | sed -e 's/-alpha./a/' -e 's/-beta./b/'
> > ```
> 
> why not `poetry version -s`?

Indeed, now it's supported https://python-poetry.org/docs/cli/#version!

**Comment by epogrebnyak** [comment]
I was so happy when I found the -s flag!

ср, 24 авг. 2022 г. в 18:34, Adrià Romero-López ***@***.***>:

**Comment by danielfajt** [comment]
In my case, I needed to read a version, name and description from pyproject.toml on the runtime (FastAPI docs). Alsouse it as a single source of truth. I've created a simple Poetry plugin to copy these values into src or other directory. It's available here:
 [https://pypi.org/project/poetry-plugin-pycopy](https://pypi.org/project/poetry-plugin-pycopy)

**Comment by ksdaftari** [comment]
curious for solution above does this work for editable installs, namely if i were to go and change the pyproject.toml project.version would that be automatically reflected in `__version__` using code like below

```
import importlib.metadata

__version__ = importlib.metadata.version(__package__ or __name__)
```

**Comment by maresb** [comment]
@ksdaftari, `importlib.metadata` reads the metadata from when the package was installed, so the `pyproject.toml` typically diverges from the metadata during an editable install. To combat this, I sometimes use:

```python
path_to_pyproject_toml = ...
pyproject_version = toml.load(path_to_pyproject_toml)["tool"]["poetry"]["version"]
if pyproject_version != __version__:
    raise ValueError(
        f"pyproject.toml version ({pyproject_version}) does not match __version__ "
        f"({__version__}). Please reinstall the package to avoid inconsistencies. "
        f"For example, run\n  pip install --no-deps --editable ."
    )
```

**Comment by neersighted** [comment]
An editable install is a standard metadata install plus a `.pth` marker pointing to a source tree at another location. The metadata will not be refreshed until you `poetry install`, at which point it will be rewritten. I'd suggest simply performing `poetry install` when you want to update it instead of using the workaround above, but it can work for you if you're okay coupling to Poetry in a strong fashion.

**Comment by danielfajt** [comment]
> curious for solution above does this work for editable installs, namely if i were to go and change the pyproject.toml project.version would that be automatically reflected in `__version__` using code like below. from what seeing doesnt get auto reflected (though perhaps i am having expectation that not expected?)
> 
> ```
> import importlib.metadata
> 
> __version__ = importlib.metadata.version(__package__ or __name__)
> ```

If you would install your package into venv as editable, you probably don't need that plugin. All it does is that it adds new poetry command "pycopy" which when executed copies values to output file (e.g. __init__.py). And it is executed with every "poetry version * " command as well to update the output file. 

But what do I plan to do in the next version is to add git tag with poetry version bump automatically. Also, to update k8s deployment file or helm with that version. The idea is simple: keep the single source of truth within pyproject.toml.

**Comment by Raphencoder** [comment]
This is my workaround for a non package project
```
import toml

app_version = toml.load("pyproject.toml")["tool"]["poetry"]["version"]
```

**Comment by louis030195** [comment]
so many messages, yet no one-liner

```bash
python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])'
```

in my makefile

```make
VERSION="$(shell python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')"
```

**Comment by juanmirocks** [comment]
It's got even easier with Python 3.11 and the new built-in `tomllib` module. For instance:

```python
import tomllib

with open("pyproject.toml", "rb") as f:
    _META = tomllib.load(f)

NAME = _META["tool"]["poetry"]["name"]
VERSION = _META["tool"]["poetry"]["version"]
DESCRIPTION = _META["tool"]["poetry"]["description"]
```

Having said that, it would still be better to have a standard way to do the same.

**Comment by facundopadilla** [comment]
Python 3.8:

```
pip install toml

pyproject = toml.load("pyproject.toml")

NAME = pyproject["tool]["poetry]["name"]
```

**Comment by MaxLenormand** [comment]
Can confirm @facundopadilla's method works nicely on Python 3.10 for versions:

```
import toml
from pathlib import Path

pyproject = toml.load(Path(__file__).parent.parent / "pyproject.toml") # This is in a nested directory, 2 directories down

__version__ = pyproject["tool"]["poetry"]["version"]

```

**Comment by facundopadilla** [comment]
> Can confirm @facundopadilla's method works nicely on Python 3.10 for versions:
> 
> ```
> import toml
> from pathlib import Path
> 
> pyproject = toml.load(Path(__file__).parent.parent / "pyproject.toml") # This is in a nested directory, 2 directories down
> 
> __version__ = pyproject["tool"]["poetry"]["version"]
> ```

@MaxLenormand yeah! I have other project with the same code and works without problems :)

**Comment by sinoroc** [comment]
@MaxLenormand @facundopadilla This can not possible work once installed. The `pyproject.toml` file is not in the wheel, and is of course never installed.

**Comment by ksdaftari** [comment]
yea i ran into same issue @sinoroc mentions above. I saw no way around just maintaining version in too places (in pyproject.toml and with `__version__` global variable within python package file. What I ended up doing to ensure consistency between these values was have automated test that used code like above examples to pull version from pyproject.toml and test matched my global variable (then at least in CI had them match).

**Comment by clintonroy** [comment]
Please, don't parse a file that's already been parsed for you. Use something like importlib.metadata.version('my-distribution') that will work with all python packages.

**Comment by sinoroc** [comment]
@ksdaftari You do not need to maintain the version string in more than one place. If you do, then I guess you are doing something wrong. Really `importlib.metadata.version('Foo')` will get you the version string of `Foo`.

**Comment by maresb** [comment]
Note that `importlib.metadata.version('Foo')` only reports the last installed version. If you have an editable install and you update your `pyproject.toml` (e.g. after a `git pull`), the result from `importlib.metadata.version('Foo')` won't be updated.

My code snippet above handles all these cases. If `pyproject.toml` can't be found, it just uses the version value from `importlib.metadata.version('Foo')`. But if `pyproject.toml` is found and there is a mismatch, then an exception is raised.

This is helpful when you have developers editing code in an editable install, and you need to make sure the reported version remains up-to-date without having to remind the developers to reinstall the code each time there's a version bump.

I'm not sure why @sinroc gave me a :-1: above?

**Comment by sinoroc** [comment]
@maresb It seems you are favoring development over production. I really would not want this [whole block of code](https://github.com/python-poetry/poetry/issues/273#issuecomment-1315797467) to run each time the module/package is imported, knowing that this whole block of code is only there to fix a broken development workflow. Because this seems to be what it is about: fixing a broken development workflow. In production the installed version can not be different from the version in `pyproject.toml` because there is no `pyproject.toml`. I recommend you fix your development workflow: anytime `pyproject.toml` gets modified then the command `poetry install` has to be executed. Maybe there is a way for you to enforce this.

**Comment by maresb** [comment]
As I wrote immediately after the code block, I agree that one shouldn't run it in production. It's easy to take precautions against that happening, e.g. only execute the `try:` block if a particular environment variable is set.

> I recommend you fix your development workflow: anytime `pyproject.toml` gets modified then the command `poetry install` has to be executed. Maybe there is a way for you to enforce this.

Isn't that exactly what my code block already does??? It always uses `importlib.metadata.version` but informs the developer if they forgot to reinstall.

**Comment by sinoroc** [comment]
@maresb My point is: this should be solved in the development tooling, this does not belong in the code itself. And it is made even worse by the fact that it is running unconditionally on import.

Maybe the Poetry commands such as `poetry version`, `poetry run`, and so on should do this kind of check and warn: "_the content of `pyproject.toml` has changed since last run of `poetry install_" or something like that.

I also believe that having a `__version__` variable is unnecessary. At the very minimum the value should be computed lazily. So that the retrieval of the version string happens when `__version__` is actually accessed, not when the module is imported.

**Comment by maresb** [comment]
> this should be solved in the development tooling

I don't see how Poetry could address this since a version change in `pyproject.toml` can be easily triggered without any interaction from the `poetry` CLI. In particular, `git checkout` or `git pull` may change the version number. I suppose one could attack this with post-checkout and post-merge commits, but that sort of tooling is fairly uncommon.) I'm fairly sure that any robust solution must involve changing the way Python handles metadata for editable installs.

> I also believe that having a `__version__` variable is unnecessary. At the very minimum the value should be computed lazily. So that the retrieval of the version string happens when `__version__` is actually accessed, not when the module is imported.

I find `__version__` to be a very practical quasistandard. I like being able to simply type something like `np.__version__` to inspect version numbers. But I do agree it would be nice to compute it lazily. Note that PEP 562 provides a mechanism which could accomplish this, but that would require some really gnarly looking boilerplate.

**Comment by sinoroc** [comment]
Use `importlib.metadata.version('numpy')` instead of `np.__version__`. This is standard. I guess you @maresb know this already (and you might have your own reason to want to do things differently), but I repeat it any chance I get anyway because people less informed than you keep doing the same mistake of ignoring this advice thinking their own use case is special when really it is not.

Maybe a post checkout git hook could help indeed, no idea if it exists. My thinking is that sooner or later you will need to run a poetry command, so maybe poetry could do a quick check to make sure that the editable installation metadata is up-to-date with the content of `pyproject.toml`. Honestly this kind of thing was never a problem for me, I am not sure in which circumstances it can happen to be an issue worth this much worry and workaround.

**Comment by rcousens** [comment]
I don't claim to be a Python master by any means, but I wrote this in my `__version__.py` file:

```python
import importlib.metadata
import tomllib

try:
    with open("pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
    __version__ = pyproject["tool"]["poetry"]["version"]
except Exception as e:
    __version__ = importlib.metadata.version('bop')
```

Seems to work for local development when the package is installed in edit mode, and then when distributed. Version number is correct and allows me to centralise on `pyproject.toml`. Awesome!

**Comment by MaxLenormand** [comment]
> @MaxLenormand @facundopadilla This can not possibly work once installed. The `pyproject.toml` file is not in the wheel, and is of course never installed.

Late to the party but yes, I quickly realised this wasn't going to work

I have dropped this since. I'm not sure what the best approach is to handle this

**Comment by sinoroc** [comment]
>  I'm not sure what the best approach is to handle this

@MaxLenormand What do you mean? It is a solved problem, use `importlib.metadata.version('NameOfInstalledDependency')`.

**Comment by vengroff** [comment]
Here is what I put in `__init__py` in my top-level package. It's a combination of some of the ideas above:

```python
import importlib.metadata
from pathlib import Path

version = "unknown"

try:
    # Try to get the version of the current package if
    # it is running from a distribution.
    package = Path(__file__).parent.name
    metadata = importlib.metadata.metadata(package)

    version = metadata["Version"]
except importlib.metadata.PackageNotFoundError:
    # Fall back on getting it from a local pyproject.toml.
    # This works in a development environment where the
    # package has not been installed from a distribution.
    import toml

    pyproject_toml_file = Path(__file__).parent.parent / "pyproject.toml"
    if pyproject_toml_file.exists() and pyproject_toml_file.is_file():
        version = toml.load(pyproject_toml_file)["tool"]["poetry"]["version"]
        # Indicate it might be locally modified or unreleased.
        version = version + "+"
```

**Comment by sinoroc** [comment]
@vengroff Why? Why is this code necessary? Why is having a `version` variable necessary? Anyone who wants to know the version string of your library can run `importlib.metadata.version('name-of-library')`. And, no `Path(__file__).parent.name` is no a reliable way to obtain the name of the library (you likely get the name of the import package, but that is not the same thing, they might be equal, but not the same thing). I really do not understand which problem this whole thing is trying to solve, and at what cost. This could all be a single function call to the standard library.

**Comment by sinoroc** [comment]
@vengroff Be mindful that this creates a run time cost (import time even!) on all production users only for some slight developer comfort. I do not have any use case in mind where it would make sense to compute the value of `version` at import or even to have the `version` variable at all.

**Comment by juanmirocks** [comment]
@sinoroc I personally need to have access to the version variable in various cases:

* Show library version in CLI help
* Show API version in REST API documentation
* Return API version in some/all REST API outputs (for better transparency with the client)

I don't think I'm alone and so I find having easy access to the version variable important.

**Comment by sinoroc** [comment]
@juanmirocks All those are legitimate use cases and can be done with `importlib.metadata.version('name-of-library')`. And I do not see any reason to store this value in a global variable (computed at import-time). Maybe the value could be cached in order to avoid reaching to `importlib.metadata` more than once, but I have no idea if it is necessary or worth it.

**Comment by vengroff** [comment]
I forgot to follow up with what I did following the previous messages in this issue from a couple weeks ago. 

For the reasons @juanmirocks mentioned among others, it can be nice to have the version available as `package.version` or `package.__version__`. And if, as in the API case mentioned, you want to easily tell whether you are running a dev or released server, you can make the version of unpackaged code come from `pyproject.toml` but look different, you have more work to do. If you don't want to execute that code at import time, which was @sinoroc's objection, you can hide it in a function triggered by getting the attribute with `package.__getattr__`. And you can cache it so the work only happens once per process. I put all those together and ended up with this in my `__init__.py`:

```python
from typing import Any
from .impl.exceptions import CensusApiException
import importlib.metadata
from pathlib import Path

__package_version = "unknown"


def __get_package_version() -> str:
    """Find the version of this package."""
    global __package_version

    if __package_version != "unknown":
        # We already set it at some point in the past,
        # so return that previous value without any
        # extra work.
        return __package_version

    try:
        # Try to get the version of the current package if
        # it is running from a distribution.
        __package_version = importlib.metadata.version("my_package_name")
    except importlib.metadata.PackageNotFoundError:
        # Fall back on getting it from a local pyproject.toml.
        # This works in a development environment where the
        # package has not been installed from a distribution.
        import toml

        pyproject_toml_file = Path(__file__).parent.parent / "pyproject.toml"
        if pyproject_toml_file.exists() and pyproject_toml_file.is_file():
            __package_version = toml.load(pyproject_toml_file)["tool"]["poetry"][
                "version"
            ]
            # Indicate it might be locally modified or unreleased.
            __package_version = __package_version + "+"

    return __package_version


def __getattr__(name: str) -> Any:
    """Get package attributes."""
    if name in ("version", "__version__"):
        return __get_package_version()
    else:
        raise AttributeError(f"No attribute {name} in module {__name__}.")
```

**Comment by sinoroc** [comment]
@vengroff Yes, this seems like this would have less technical side effects and drawbacks.

But this is a lot of code for -- in my opinion -- very little gain, and this gain is strictly limited to the development phase, which is -- again in my opinion -- what one should optimize for.

**Comment by juanmirocks** [comment]
From my experience, many packages are in the "development phase" FOREVER or for a VERY LONG TIME. They never get "distributed" and yet they keep running for a long time.

For those scenarios, either we have some code similar as to what @vengroff suggested (which IMHO is not long; it's mostly comments), or otherwise developers need to keep remembering to install from time to time their dev packages (`poetry install`) and then they can make use of the updated `importlib.metadata.version("<my_package>")`.

I guess that second option is acceptable though feels strange to me at least. Nonetheless, if that's so far the "recommended" approach, it would be nice adding it to the poetry docs somewhere. Do you agree? I guess some people don't know such option exists (me included before) and that's why the confusion and the many comments in this issue.

**Comment by vengroff** [comment]
There is a package for this now. I factored a variation of the code above to a new package called `usingversion`. See https://github.com/vengroff/usingversion.

Things get just a little more complex when you want to move this functionality out of a package's `__init__.py`. The usage
is two lines (see the README.md) but it still feels a bit clunkier than it needs to be. If you have suggestions or other comments, open an issue or discussion in the [`usingversion`](https://github.com/vengroff/usingversion) repo.

**Comment by sinoroc** [comment]
> it would be nice adding it to the poetry docs

Note that it is not specific to Poetry. No build backend or dev workflow tool that I know of does it any better than Poetry, because that is the state of the art as far as I can tell. If packaging metadata changes (which includes the version) then the thing must be reinstalled (to take the new metadata into account), even if the thing is installed as "editable".

I am not saying things can not be improved. Maybe someone will come up with a good solution to handle updating metadata transparently for editable installations.



> From my experience, many packages are in the "development phase" FOREVER or for a VERY LONG TIME. They never get "distributed" and yet they keep running for a long time.

Without thinking much about this... I wonder what is the point of bumping the version number in such a use case then? How does that work? You `git pull` some new code, but do not run `poetry install` right after?

**Comment by juanmirocks** [comment]
@sinoroc I see your points. I was referring rather to developers working on some tool, e.g. a REST API web server, which returns the version somewhere, expecting to see the version changed in `pyproject.toml` immediately reflected in the API output.

From a user point of view, the version property in the `pyproject.toml` is poetry's "responsibility", after all the property is called `tool.poetry.version`. And that's why I think some developers using Poetry expect to get that "live" version for a developing/running application in some way. That's why I still think that a small documentation comment somewhere would be helpful. My 2 cents.

**Comment by sinoroc** [comment]
So I just tested `poetry version major` and it does not trigger the update of the installed metadata (`python run pip show my-project`). Maybe it should. Maybe it has already been suggested, I do not know. Right now, one still needs to run `poetry install` for the installed metadata to be updated. On the other hand `poetry version` shows the new version (i.e. not what is the installed metadata).

And yes, maybe it is worth a note somewhere that updating the installed metadata (via editing `pyproject.toml` directly or via the command line), requires running `poetry install`. I do not know what is the best location for such a note in the documentation.
