### ISSUE TITLE
Dependency on boto3 doesn't install botocore

### ISSUE THREAD

**Issue by radix** [sdispater/poetry#37]
I have a project that depends on boto3, but for some reason botocore isn't being installed. I checked the boto3 wheel and I see that it has a botocore dependency listed in METADATA, and pip also fetches botocore when installing into a virtualenv, so I think this might be a poetry bug.

```
{}radix@pop-os:~$ poetry new testboto3
Created package testboto3 in testboto3

{}radix@pop-os:~$ cd testboto3/

{}radix@pop-os:~/testboto3$ cat pyproject.toml
[tool.poetry]
name = "testboto3"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "*"
boto3 = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.5"

{}radix@pop-os:~/testboto3$ poetry install
Creating virtualenv testboto3-py3.6 in /home/radix/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...


Package operations: 7 installs, 0 updates, 0 removals

Writing lock file

  - Installing attrs (17.4.0)
  - Installing more-itertools (4.1.0)
  - Installing pluggy (0.6.0)
  - Installing py (1.5.3)
  - Installing six (1.11.0)
  - Installing boto3 (1.7.0)
  - Installing pytest (3.5.0)

{}radix@pop-os:~/testboto3$ poetry run python
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radix/.cache/pypoetry/virtualenvs/testboto3-py3.6/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/radix/.cache/pypoetry/virtualenvs/testboto3-py3.6/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
ModuleNotFoundError: No module named 'botocore'
```

**Comment by sdispater** [comment]
This a known issue but is not caused by poetry directly.

Basically, poetry uses the PyPI JSON API to get packages information to avoid having to download every packages to inspect dependencies.

Here is the JSON payload for boto3: https://pypi.org/pypi/boto3/json. As you can see in `info.requires_dist`, which represents the dependencies, it's empty. So, naturally, poetry can't pick up the `boto3` dependencies.

This is an issue of `boto3` when they upload their packages without passing all the necessary metadata. They should use `twine` to upload the package (or even `poetry` ;-)) to avoid that.

For the time being, you might consider adding `botocore` to your dependencies to workaround the issue.

**Comment by radix** [comment]
This makes me really sad :( Clearly the python ecosystem is not ready for people to actually use the metadata API on PyPI. (I'm surprised it requires the uploading tool to specify it, instead of PyPI just analyzing the contents of the uploaded file...) I noticed there are other cases of this in my dependency tree as well.

Is there any possibility of allowing a slow-mode that does download packages in order to access their metadata?

**Comment by sdispater** [comment]
I know and that's why tools like `poetry` will help make everything consistent. You can report the issue upstream (on the `boto3` repository) to help improve things.

It's possible to activate a slow-mode, even though I consider it a hack since it's not the intended use case.

You can set a new repository in your `pyproject.toml` file which points to PyPI:

```toml
[[tool.poetry.source]]
name = 'pypi-legacy'
url = 'https://pypi.org/simple'
```

Note, however, that due to the way the dependency resolver works and the important number of releases for `botocore` it will be extremely slow the first time (on my machine it took 30 minutes to resolve dependencies). It will be much faster after that since everything will be cached. But if you use  a CI system and you do not cache the poetry's cache directory it will be slow each time.

That's why it is not the recommended approach and poetry tries to use the JSON API as much as possible.

**Comment by radix** [comment]
hi sdispater!

I recently tried again with the latest release of poetry and botocore was installed successfully, so I'm closing this.

Thank you very much for your hard work! I am very excited about poetry making working with Python projects much better.
