### ISSUE TITLE
How to add poetry to an existing project

### ISSUE THREAD

**Issue by Tajnymag** [sdispater/poetry#46]
I have an already existing project and would like to switch from pip to poetry. Basically I want to initialize an already exsting folder.

How should I do it? It seems poetry doesn't support this.

**Comment by sdispater** [comment]
There is no way currently to migrate a project to `poetry` without building your `pyproject.toml` file by hand.

And, to be honest, I don't think it's a feature I will add since there are multiple ways to declare your dependencies in Python at the moment (which I want to standardized with `poetry`): in a `requirements.txt` file, in `setup.py`, in `setup.cfg`.

So, hopefully, you do not have too many dependencies and it should be a quick process with the `poetry add` command.

**Comment by Tajnymag** [comment]
@sdispater I didn't mean to migrate a project. I meant to init poetry in an existing directory. Similar to what "git init" or "npm init" do.

**Comment by sdispater** [comment]
Currently, no, it's not possible but that's something I'd like to add.

I will see if I can add it in the next feature release.

**Comment by Tajnymag** [comment]
@sdispater OK, thank you.

**Comment by alairock** [comment]
This. So much this. This is absolutely needed for a CLI like this.

**Comment by sdispater** [comment]
Release `0.10.0` adds a new `init` command which covers this use case.

**Comment by kakulukia** [comment]
Awesome .. gonna try this tomorrow!

**Comment by beorn** [comment]
```console
% poetry init
% poetry add `cat requirements.txt`
```

**Comment by StevenACoffman** [comment]
This works for me in bash:
```
for item in $(cat requirements.txt); do   poetry add "${item}"; done
```

**Comment by ST33LDI9ITAL** [comment]
FOR /F "usebackq delims==" %i IN (`cat requirements.txt`) DO poetry add %i
on Windows

**Comment by caleb15** [comment]
```cmd
FOR /F "usebackq delims==" %i IN (cat requirements.txt) DO poetry add %i
```

This doesn't add packages with version pinning.

ex: it adds Django instead of Django==1.11.20

I would suggest removing the `"usebackq delims=="`

**Comment by ekhaydarov** [comment]
I happened to have an existing pyproject.toml file and it just throws an error that it already exists. meaning i manually need to add the poetry stuff. Small thing, but some feedback nonetheless

**Comment by lugodev** [comment]
I've done it this way:

```python
import subprocess

def main():
    with open('requirements.txt', 'r') as file:
        text = file.read()
        deps = text.split('\n')
        for dep in deps:
            if dep != '':
                d = dep.split('==')
                subprocess.call(['poetry', 'add', '{}^{}'.format(d[0], d[1])])

if __name__ == '__main__':
    main()
```

Then I saw @StevenACoffman solution an felt embarrassed :smile:

**Comment by jha-prateek** [comment]
> FOR /F "usebackq delims==" %i IN (`cat requirements.txt`) DO poetry add %i
> on Windows

`for /F "tokens=*" %i in (requirements.txt) do poetry add %i `

**Comment by jaepil-choi** [comment]
Yeah `init` command was added but what I would expect is installing all stocks components - .toml, foo_projectname/, test_foo_projectanme/, README.rst. Current init option prompts an empty .toml file, which doesn't seem necessary.

**Comment by cglacet** [comment]
Are we really supposed to put all requirements in poetry (`pip freeze` output)? Or are we only supposed to add build dependencies?

**Comment by sinoroc** [comment]
@cglacet 

***Build dependencies*** go into the `requires` field of the`build-system` section. Typically for a poetry project the only build dependency is poetry itself or poetry-core for more recent projects:

```
[build-system]
requires = ['poetry-core>=1.0.0']
# ...
```

***Install dependencies*** are the things that you want to be installed alongside your project, typically because your code imports them at run time. So the recommendation is to list only the libraries your code actually imports directly. And not the dependencies of your dependencies. Those belong in the `[tool.poetry.dependencies]` section. 

***Development dependencies*** are typically the tools you use while working on your code, so things like _pytest_, _pylint_, _black_, etc. and they belong in the `tool.poetry.dev-dependencies` section.


***pip freeze*** would give you everything that is currently installed in the environment, so it contains your dependencies but also the dev dependencies and the dependencies of your direct dependencies and the dependencies of your dev dependencies. So `pip freeze` is definitely not the thing that you want.

**Comment by cglacet** [comment]
@sinoroc Thanks for the very quick and precise answer. I was questioning the answers proposing to directly add everything from `requirements.txt` which I think in practice often contains the whole `pip freeze` output.

**Comment by sinoroc** [comment]
@cglacet I didn't read the older messages in details, but yes, seems like potentially "_dangerous_" advice.

It depends what `requirements.txt` contains exactly. Sometimes it is the raw output of `pip freeze` sometimes it is a meaningful list. There is no rule. People can put whatever they want in it.

If it is a carefully curated list of direct top level install dependencies (i.e. import dependencies), then it is all good. Otherwise, it could lead to issues down the line.

For sure do not add the output of `pip freeze` to your `pyproject.toml`.

**Comment by vcheckzen** [comment]
Windows PowerShell

```powershell
Get-Content requirements.txt | ForEach-Object { poetry add $_.split('==')[0] }
```

**Comment by ST33LDI9ITAL** [comment]
I can't believe this is still an issue...

**Comment by lugodev** [comment]
I think they should include it as a native feature.

**Comment by rhtenhove** [comment]
How is this an issue if you can just do:
1. `cd project`
2. `poetry init -n`
3. Realize your dependency management was awful so far
4. `poetry add package` for each of your project dependencies
5. `poetry add -D package` for each of your development dependencies
6. Be done and happy you took the time to provide some sensible structure to your project, and suddenly have this great overview after thinking through what your project really depends on.

The other stuff, such as `README.rst`, `project/` and `tests/`, doesn't make sense for an existing project since those are already there, or your project needs a manual cleanup. `poetry` can not ever know how to fix up your current project structure, because it did not adhere to the poetry expected standard, so it can be anything.

You can of course do `poetry new project_name` and move your stuff in there, if you really want the base structure. But again, can't do this automatically, because poetry wouldn't be able to know what to do with existing conflicting files.

**Comment by ST33LDI9ITAL** [comment]
Well, obviously if people think it's an issue... then it's an issue...
especially if people have to make workarounds for functionality.

**Comment by emlazzarin** [comment]
There are many projects that already have `pyproject.toml` but lack a Poetry section, leading to an error like:

```
[tool.poetry] section not found in /Users/elazzarin/code/pytrends/pyproject.toml
```

It seems relatively straightforward to resolve by hand, so may be helpful to add to the `poetry init` process if someone wants to migrate to Poetry smoothly.
