### ISSUE TITLE
hash mismatch error when a wheel has been uploaded to same version since the last lock

### ISSUE THREAD

**Issue by radix** [sdispater/poetry#51]
This is a fun one. My project depends on `pluggy = "^.0.6.0"` , which up until three days ago only had a `.tar.gz` release. Then they uploaded some wheels with the same version. I ran a `poetry install` today, and it seems that it's preferring the new .whl files (as it should), but then not realizing that this is a different file from the .tar.gz, so it shouldn't really be comparing to that old hash.

Here's the error I'm getting:

```
  - Installing pluggy (0.6.0)

  [VenvCommandError]

  Command ['pip', 'install', '--no-deps', '-r', '/tmp/pluggy-0.6.0iCCMcYreqs.txt'] errored with the following output:

  Collecting pluggy==0.6.0 (from -r /tmp/pluggy-0.6.0iCCMcYreqs.txt (line 1))

    Downloading https://files.pythonhosted.org/packages/82/05/43e3947125a2137cba4746135c75934ceed1863f27e050fc560052104a71/pluggy-0.6.0-py2-none-any.whl

  THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the packag

  e contents carefully; someone may have tampered with them.

      pluggy==0.6.0 from https://files.pythonhosted.org/packages/82/05/43e3947125a2137cba4746135c75934ceed1863f27e050fc560052104a71/pluggy-0.6.0-py2-none-any.whl#sha2

  56=d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c (from -r /tmp/pluggy-0.6.0iCCMcYreqs.txt (line 1)):

          Expected sha256 7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff

               Got        d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c
```

**Comment by radix** [comment]
Actually, it may be a little more convoluted, I'm not really sure https://github.com/pytest-dev/pluggy/issues/134

but i think the takeaway may be the same: poetry should probably be including the filename (or even full URL that was downloaded) in the lock file, so it can consider that when comparing hashes

**Comment by sdispater** [comment]
Yes I encountered this as well. The maintainers of `pluggy` reuploaded files and tampered with a previous release (which PyPI should prevent in my opinion) which leads to this error.

`poetry` caches a lot of information to avoid hitting PyPI each time when resolving dependencies so it won't be able to pick up the new hashes.

This case is rare, fortunately, so for the time being you can add the new hashes to your `pyproject.lock`.

That being said, the next `0.9.0` release will introduce a new `cache:clear` command to clear specific hashes when this occur. This would look like this:

```bash
poetry cache:clear pypi:pluggy:0.6.0
```

And unfortunately  your proposal won't work since the file downloaded on your machine might be different from the one downloaded on someone else's due to wheels targeted at different systems and platforms. That's why when `poetry` downloads files it passes all hashes to check.

**Comment by radix** [comment]
I don't think they "tampered" with a previous release - they did not modify any existing files, and PyPI does disallow that, as I understand it. They did two things:


1. added `.whl`s to releases that only had `.tar.gz`
2. deleted a universal wheel and added two other wheels (py2 and py3)

so no existing file was replaced with different content. This is why I think poetry should keep track of the original filename: if downloading a different file, it doesn't make sense compare to the same old hash.

As for what you said about the "file downloaded on my machine might be different from the one downloaded on someone else's", doesn't that mean that poetry would break if a .lock file is shared between e.g. a Windows and a Linux machine?

**Comment by birkenfeld** [comment]
As a follow-up to the linked Pygments issue, which sent us maintainers scrambling to figure out what is wrong with our project, only to discover this issue:

Since it's apparently been decided that this is not worth fixing, let me just suggest here to change the error message to include a note that recently added distribution files with *the same version* can also trigger this.

**Comment by ento** [comment]
I ran into this with [python-crontab 2.6.0](https://pypi.org/project/python-crontab/2.6.0/#files) and got it fixed by doing `poetry lock --no-update --no-cache`, which took 10+ minutes, but if I knew that I could [clear the cache for a single package](https://python-poetry.org/docs/1.2/cli/#cache-clear) now (I'd only skimmed this thread and didn't spot the mention of a plan to add that command), it would've been quicker.

(Leaving this comment here in hopes that it's helpful for other people encountering the same issue)
