### ISSUE TITLE
Please add to the docs the reasons why this tool exists (on a separate page)

### ISSUE THREAD

**Issue by KOLANICH** [sdispater/poetry#542]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hello. I don't understand the idea behind this tool.

There exists `setuptools` dealing with building packages. It [has been allowing to declare the stuff in `setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) for quite a long time. Though it is not `pyproject.toml`, I guess it can be moved there with time https://github.com/pypa/setuptools/issues/1160 . So I don't understand why to create a yet another package manager and build system (in the best case it would be ignored by people and your effort would be just wasted, in the worst one we'll get a fragmented ecosystem where a user would have to install and support in own packages a serpentarium of different package managers and their dependencies and take care on what package manager to use), not to improve the existing packages.

Could you clarify this in the docs and `README.md`?

**Comment by azag0** [comment]
[I'm not an author of Poetry, just a happy user.] Please, make yourself first familiar with the ideas in PEPs [517](https://www.python.org/dev/peps/pep-0517/) and [518](https://www.python.org/dev/peps/pep-0518/) before making comments such as this one. `setup.cfg` is specific to Setuptools, which is one possible way how to build Python packages, but there is no reason to think it's the only or the best one. Python now officially supports (via the PEPs above) the concept of having multiple build systems for packages. You can think of it as free market, where the best build tool wins. Poetry is one of such build tools.

**Comment by KOLANICH** [comment]
>Python now officially supports (via the PEPs above) the concept of having multiple build systems for packages. 

And this IMBO was a big mistake: fragmentation is not a good thing, the main benefit of python ecosystem is its uniformity: when one needs calculations, he uses numpy, when he needs math, he uses scipy, when he needs <something>, he uses <some package everyone else uses when he needs that>. This is beneficial:
1. all the features are in the same package, no situation when a dev needs 2 features when one is in one package and another one is another package
2. no need to develop the same features for many packages.
3. Usage of that package is expected, a dev of some auxilary library doesn't have to implement support for multiple packages in it.

And when one needs packaging, he uses pip and setuptools. And when one needs to write an addon adding a custom packaging stage, he writes an addon supporting only setuptools, not the serpentarium of differrent packages.

>You can think of it as free market, where the best build tool wins. Poetry is one of such build tools.

Free market is definitely a good thing, but here we are not selling products, but working to achive the common goal of having a good packaging system, so competition here is bad thing and cooperation is the good one. One good package manager is better than 100 not so good ones. So one should really have good reasons to start reimplementing something already implemented rather than improving it.


So I consider having a bunch pckages for the same thing as bad and harmful. What python ecosystem really needed is the declarative sdist manifest requiring no code execution to build a wheel, so the tooling can assume that, and this format is the `setup.cfg` supported by setuptools. If one is not satisfied with pip and setuptools, IMHO he should improve them, not to start own replacements.

**Comment by rooterkyberian** [comment]
Currently we already have a comparison of `poetry` vs `pipenv`. The same maybe done for `poetry` vs bare `setup.cfg` (or setuptools as a whole). If you think that is needed its best to create a PR for it.
To get you started I would suggest reading through https://www.python.org/dev/peps/pep-0518/ and `pipenv` and `poetry` discussion. `pipenv` has less functional overlap with `setup.cfg`, so it maybe easier to see looking at it alone features that `poetry` offers over `setuptools` alone (such as dependency locking, single configuration file, virtualenv management, and some basic project bootstraping). Then there are things that differ between `pipenv` and `poetry`, and those among other is that `poetry` tries to free you from `setup.cfg` and `setup.py` - you can read some of recent discussion about it here: https://github.com/sdispater/poetry/pull/488.

The fragmentation/free market discussion is a somewhat idealistic side topic, which I'm unsure should be entertained here, but I hope you do realize that python packaging system has gone a long way since Python emergence and it wasn't a linear development. I see your point about wasted effort, but then again, just talking about things doesn't change much and it is much easier to prove worth of your ideas by giving them a chance to prove themselves - that is implementing them, and hoping world will be better for it. If it doesn't pan out, welp, at least you tried.

**Comment by orlnub123** [comment]
I'd heavily recommend reading https://snarky.ca/clarifying-pep-518/, it's a great resource on the topic.

@KOLANICH I don't fully understand the implementation and how all the pieces come together but I don't think your analogy on uniformity is correct. Choosing to import and use numpy is an option, you aren't forced to use it instead of a less popular package, or even your own. This is unlike the earlier situation, where you have to use setuptools/distutils if you want to support pip, which every other developer uses.

One thing that I don't like currently and something that contradicts the above is that you're forced to use Poetry in order to install a Poetry-dependent package from source. Thankfully that won't last long as [PEP 517 support is getting added to pip.](https://github.com/sdispater/poetry/issues/321#issuecomment-406623290)

**Comment by xsduan** [comment]
Having used both quite a bit (moved to poetry because of setup.py generation and because pipenv broke) here’s my reasons for poetry being worth it:

- Close mapping to npm cargo etc functionality. I was frankly kind of upset when pipenv didn’t allow for an easy mechanism for having a git repository as a depedency, and it didn’t generate setup.py for you. I’d heard of poetry in passing so I picked it. Maybe one of the other ones is better? Idk
- pipenv has this weird “marketing” thing about it. I don’t care about user testimonials if I’m looking at the docs. Maybe it’s a minor thing but it pushed me over the edge in my reasons to move away from pipenv. 
- for some reason the lock mechanism for pipenv absolutely, utterly broke in my system for me and just for me. Everyone at my job can still use pipenv fine so if for no other reason this is the advantage of having more than one option.
- back when pipenv did work it would be about 10-20 times slower than poetry is now at locking my projects. (Windows) Dunno what the difference is but it made a huge difference. 

This isn’t to say you should drop pipenv for poetry  if pipenv is still working for you just because, but it has been a lifesaver and a huge convenience for package development for me personally.
