### ISSUE TITLE
unable to install uvicorn

### ISSUE THREAD

**Issue by karansthr** [sdispater/poetry#564]
```
» poetry add uvicorn
Using version ^0.3.16 for uvicorn

Updating dependenciesResolving dependencies... (0.0s)
[SolverProblemError]
The current supported Python versions are 3Because no versions of uvicorn match >0.3.16,<0.4.0
 and uvicorn (0.3.16) depends on websockets (>=6.0), uvicorn (>=0.3.16,<0.4.0) requires websocke
ts (>=6.0).
Because websockets (6.0) requires Python >=3.4 and no versions of websockets match >6.0, websockets is forbidden.Thus, uvicorn is forbidden.
So, because droplinks depends on uvicorn (^0.3.16), version solving failed.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extra
s EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <n
ame> (<name>)...
```

**Comment by jacebrowning** [comment]
Please share your `pyproject.toml`. I suspect you need to set `python = "^3.4"`.

**Comment by sdispater** [comment]
Next time, can you please fill in the appropriate issue template?

Anyway, from what I can tell from the `SolverProblemError` is that this is the expected behavior.

- Your project supports Python 3 which is interpreted by Poetry as `^3.0` (`>=3.0,<4.0`).
- `uvicorn (0.3.16)` depends on `websockets (>=6.0)`.
- `websockets (6.0)` requires Python >=3.4 which is not fully compatible with your project's Python versions.
- The resolver warns you about the conflict.

This is the expected behavior of the dependency resolver. To fix this you have three choices:

- Change your project's Python requirement to `^3.4`.
- Make your `uvicorn` dependency only necessary for Python ^3.4: `uvicorn = {version = "^0.3.16", python = "^3.4"}`
- Find a compatible `uvicorn` version, which is `uvicorn (0.2.12)` which in turn will make you downgrade `websockets` to `4.0.1`.

**Comment by karansthr** [comment]
changed python requirement to `^3.4` and its working! thanks
