### ISSUE TITLE
can't install `testtools` because of circular dependency on `fixtures`.

### ISSUE THREAD

**Issue by radix** [sdispater/poetry#62]
I realize it seems like this was an intentional decision to not support circular dependencies, but `testtools` apparently has a circular dependency on `fixtures`. It seems they refuse to break this dependency, but it is apparently not a runtime dependency -- one of them is build-time. https://github.com/testing-cabal/testtools/issues/236

I'm not sure if there's a way to resolve this -- does testtools or fixtures need more metadata specified with their dependencies? can poetry just allow circular dependencies?

**Comment by sdispater** [comment]
`poetry` was designed so that circular dependencies would lead to an error. Circular dependencies are bad by definition, even though in this case the resolver could find a solution.

And both are runtime dependencies:

- For testtools: `Requires-Dist: fixtures (>=1.3.0)`
- For fixture: `Requires-Dist: testtools (>=0.9.22)`

That was never a problem for them before because `pip` doesn't come with a dependency resolver and thus would install everything without picking up the circular dependency.

So, for now, handling this case would require to change the implementation of the resolver and this is not something I want to tackle as of yet since there is more pressing matters.

However, I might come back to it at some point.

**Comment by radix** [comment]
I see, indeed I misread the ticket and now see that it's a runtime dependency and not a build-time dependency. :cry:

**Comment by sdispater** [comment]
Release `0.10.0` is out and should fix this issue.
