### ISSUE TITLE
Poetry fails to get version

### ISSUE THREAD

**Issue by polski-g** [sdispater/poetry#739]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 16.04 with python 3.7.1
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/polski-g/2fe88bea08fff81357a306c75c7a482b

## Issue

I am unable to install djurl: https://github.com/polski-g/djurl

It sounds related to https://github.com/sdispater/poetry/issues/673 but even installing setuptools has no effect.

I can checkout the djurl repo, and then run "poetry run python setup.py egg_info" and it execute fine.

**Comment by tom-mi** [comment]
I have the same issue when trying to install tf-openpose (https://www.github.com/ildoonet/tf-openpose).

**Comment by jimrthy** [comment]
Hopefully useful information:

I just ran into something that has the same symptoms using one of our internal libraries running inside a docker build.

When poetry runs `venv.run("python", "setup.py", "egg_info")` to try to figure out the version number, it seems to be running a wrong version of python (my guess is the default system python2 vs. the python3 that I want).

If I put a symlink to `python3` on the PATH as `python`, this works.

My best guess about my version of this issue is that this step happens before poetry sets up the venv.
