### ISSUE TITLE
Support customizable POETRY_HOME

### ISSUE THREAD

**Issue by dcramer** [sdispater/poetry#775]
It would be nice to define where poetry gets installed (via get-poetry.py).

By reading the docstring I had assumed it would work in $POETRY_HOME, but that was quickly disproven.

Ideally this could be defined via an environment variable (POETRY_HOME) or via a flag to get-poetry.py.

**Comment by dcramer** [comment]
Aside, this is to make things like travis and Docker easier to configure. Example of me continually guessing and messing this up is available here:

https://github.com/getsentry/zeus/pull/166

Hopefully by the time you've read this I have it all functional ;)

**Comment by hangtwenty** [comment]
Two options for workaround (in case someone drops by here, who cannot wait for #794 to be merged)

* vendor the updated  `get-poetry.py` into the repository then make the necessary edit (same as #794) 
* and/or hacking `HOME` because the only usage of it in get-poetry.py is `HOME = os.expanduser('~')`, and it bases `POETRY_HOME` off of that. _(`os.expanduser('~')` is equivalent to just getting $HOME, in Linux/Mac envs anyways.)_

it is not unsafe to override 'HOME' in a subshell, here's an example of that;

```bash
$ echo "[outer shell] HOME='$HOME'" ; (export HOME=/foobar; export POETRY_HOME=/foobar/.poetry; echo $HOME; echo $POETRY_HOME;); echo "[outer shell] HOME='$HOME'"
[outer shell] HOME='/Users/hangtwenty'
/foobar
/foobar/.poetry
[outer shell] HOME='/Users/hangtwenty'
```

**Comment by stephsamson** [comment]
#794 closes this issue.
