### ISSUE TITLE
`lock` and `update --lock` work exactly the same? Deprecate one?

### ISSUE THREAD

**Issue by butla** [sdispater/poetry#777]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Judging by the code (and the behavior) [poetry lock](https://github.com/sdispater/poetry/blob/master/poetry/console/commands/lock.py) and [poetry update --lock](https://github.com/sdispater/poetry/blob/master/poetry/console/commands/update.py) work exactly the same.

Maybe one of them should be deprecated to lessen the confusion?

Also, `lock` and bare `update` (without `--lock`) differ only in that the latter updates the lock file **and** installs into the virtualenv, right? I guess that should be clarified in the docs. I might submit a PR if I got this right.

**Comment by dmohns** [comment]
As a newcomer, I can confirm the existence of both `peotry lock` and `poetry update --lock` is very confusing. The fact that documentation for `poetry lock` is somewhat inconclusive adds to that confusion.

Assuming @butla is right, that both of them do exactly the same thing: I would suggest going a step further and not only deprecate `poetry lock` but also rename the option `--lock` to something more intuitive/suggestive for example `--lock-only`.

**Comment by seansfkelley** [comment]
I just ran into this in the documentation as well. Duplication leads to confusion!

My two cents: I would drop the `--lock` flag, under the assumption that the `lock` subcommand should be tailored to manipulating the lockfile without touching installed artifacts, and `update` is specifically for updating installations and (therefore) the lockfile too. The flag is also confusingly named... should it be `--lock-only`? As currently named, it suggests that it otherwise _wouldn't_ lock, which is obviously not the same.

Merging them into one subcommand is a bit hairy, since https://github.com/python-poetry/poetry/issues/453 is at least one reason you'd want to have a separate `lock` subcommand.
