### ISSUE TITLE
Why master have code with failed tests?

### ISSUE THREAD

**Issue by Ovsyanka** [sdispater/poetry#792]
Hello!

I just decided to try poetry and the first thing I see on the progect page is failed tests: 
![screenshot_2019-01-12_01-05-25](https://user-images.githubusercontent.com/1226722/51064001-2d788a00-1606-11e9-9a46-7a20538e858f.png). Then I checked the release [1.0.0a1
](https://github.com/sdispater/poetry/tree/1.0.0a1) and some tests is failed too. So it looks like an usual thing here. Is it some reason to have failed tests in the master?

**Comment by sdispater** [comment]
As far as I know the `develop` branch is not failing: https://travis-ci.org/sdispater/poetry/builds/469286434

And I am aware that tests are currently failing on the `master` branch however they are not due to broken functionalities only non-deterministic order when displaying dependency resolution errors.
