### ISSUE TITLE
BrokenPipeError when `poetry show -v | head -n 1`

### ISSUE THREAD

**Issue by jimbo1qaz** [sdispater/poetry#839]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04 x64, zsh
- **Poetry version**: 0.12.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: probably irrelevant

## Issue
It was suggested on the issue tracker, that to "find the virtualenv path", I run `poetry show -v` and look at the first line.

To automate that process, I tried executing `poetry show -v | head -n 1` in zsh. However when `head` closes the pipe, Poetry instead raises BrokenPipeError.

https://gist.github.com/jimbo1qaz/014f6e831af944db235e77af61339b49 (poetry show -vvv, not -v)

Is this a reasonable use case? Is it possible to catch this error and stop writing to stdout (or terminate)?

(Note: on Windows, depending on buffer size, subprocess.Popen pipes may produce OSError instead. But this is *not* a Popen pipe, but a shell pipe.)

**Comment by zmitchell** [comment]
Your traceback shows that the error lies within `cleo`. After searching for some context, it appears that `pip` faced a similar issue some time ago (see [here](https://github.com/pypa/pip/issues/4170)). It looks like the BrokenPipeError does indeed come from head closing the pipe before `poetry`/`cleo` is done writing i.e. it closes the pipe after it's read the `N` lines in a call to `head -n N`. It looks like the `pip` crew just chose to print a more helpful error message in the end, so that could be a solution here.

**Comment by jimbo1qaz** [comment]
I feel that pipenv/poetry are not designed to handle non-web apps well: both make it very difficult to activate an env when your working dir is not `cd` into the source tree. On the contrary, conda envs are global and easy to activate anywhere.

I primarily work on "project/document" desktop/CLI apps, rather than web apps. It would be nice if I could:

```
cd ~/path/to/documents
poetry activate global-editor-env  # same syntax as conda activate
poetry run editor document (or editor document)
```

instead of:

```
cd ~/code/editor-app
poetry shell
cd ~/path/to/documents
poetry run editor document` or `editor document
```

or
- opening my IDE's terminal in ~/code/editor-app, running `poetry show -v | head -n 1` (which caused this bug report)...
- opening another terminal in ~/path/to/documents, running `. ^above/bin/activate` or similar...

Should I file another bug report?

**Comment by pmav99** [comment]
You don't have to use poetry to handle virtualenvs. If a virtualenv is active, poetry will be happy to use it. So you can use pew or virtualenvwrapper or (I guess) even conda to manage your virtualenvs

**Comment by zmitchell** [comment]
Getting back to the actual error you brought up, it looks like you can avoid the error by doing this:

```
# cleo/outputs/stream_output.py
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)
```
This solution is taken from [this](https://stackoverflow.com/a/30091579) SO post. In short:
* `SIGPIPE` is sent to a process when it tries to write to a pipe that is no longer open.
* If the process doesn't handle `SIGPIPE`, then it is terminated.
* Python catches the `SIGPIPE` and raises a `BrokenPipeError`.
* This solution recovers the default behavior (`SIG_DFL`, i.e. terminating the process).

P.S. - For what it's worth, I don't really do any web development at all, and I use `poetry` all the time.

**Comment by zmitchell** [comment]
It turns out that `poetry` is using `cleo` 0.6.8, but the current version is `0.7.2`, and there are major changes to the layout of the `cleo` project between those releases. You can't just make `poetry` use the newer version of `cleo` without breaking things, so for the time being I would recommend changing those two lines in your local version of `cleo` that was installed with `poetry`.
