### ISSUE TITLE
Packages having common dependencies get removed on removing one of the package

### ISSUE THREAD

**Issue by ajitid** [sdispater/poetry#895]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- Kubuntu 18.10
- Poetry 0.12.11

## Issue

For example, `konch` and `ptpython` have dependency on `docopt`. So if I install both of these packages and then remove `ptpython`, `konch` won't run as `docopt` is missing. This happened because when `ptpython` was removed, `docopt` also got removed.

- Konch loads up variables and runs a shell
- PtPython is a shell like IPython, Bpython

I have `settings.virtualenvs.in-project = true` for Poetry.

### Reproduce using:

1. `poetry init` in a folder
1. `poetry add konch ptpython`
1. `poetry run konch init`
1. Test konch is working using `poetry run konch`. Exit out of the shell.
1. `poetry remove ptpython`
1. Try to re-run Konch using `poetry run konch`

### Actual behaviour:

Konch fails to run and complains about missing `docopt` import.

### Expected behaviour:

Konch should run.

**Comment by sdispater** [comment]
As far as I can tell, `konch` does not depend on `docopt` (see the `requires_dist` section here: https://pypi.org/pypi/konch/json).

However, they bundle a `docopt.py` file which will be removed when uninstalling the `docopt` dependency. This is expected and the issue lies with `konch` that should not bundle a `docopt.py` file and should properly depend on `docopt`.
