### ISSUE TITLE
Creating and publishing a private repo with token

### ISSUE THREAD

**Issue by alairock** [sdispater/poetry#919]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question
On the page:
https://poetry.eustace.io/docs/repositories/

The docs show how to add the username/passsword but my specific repository (gemfury) only allows me to use a token. I have attempted to add it to `repositories.fury.url` as what seems logical, but It doesn't seem to work. Any thoughts on how one might do this?

**Comment by gmaybrun** [comment]
Not sure if this is the same issue or if I should open up a separate ticket.

If I set the `[[tool.poetry.source]]` `url` to my Gemfury URL (`https://repo.fry.io/<private-token>/<org>`) then things work fine. The problem is I obviously don't want to embed my private token in `pyproject.toml`.

My ask is that there's a way to set that at runtime. For example, interpolating ENV vars -- if I could set set `url = "$GEMFURY_URL"` and it'd read that from ENV vars, I'd be happy. My current workaround is dynamically write pyproject.toml (can either use `sed` to rewrite the file, or use a `pyproject.toml.tmpl` to that gets the private source added to it and putting the actual pyproject.toml in gitignore, which is a little safer).

Both are irritating extra steps that I'd love to avoid.

**Comment by drunkwcodes** [comment]
Wrong repo?

**Comment by jasonkuhrt** [comment]
Related #910

**Comment by espoirMur** [comment]
same issue here..

**Comment by henrytseng** [comment]
Which username would you use if you have an organization setup with Gemfury?  Our `fury` CLI commands require the flag `--as` which looks like it prevents us from using poetry to push and pull.  Can anyone confirm this?
