### ISSUE TITLE
Add support for Entry Points

### ISSUE THREAD

**Issue by astronouth7303** [sdispater/poetry#927]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I do not see a way to specify arbitrary [entry points](https://packaging.python.org/specifications/entry-points/). Eg, SaltStack uses the `salt.loader` entry point.

Please add this?

**Comment by pmav99** [comment]
@astronouth7303 Perhaps you mean [this](https://poetry.eustace.io/docs/pyproject/#scripts)?

**Comment by orlnub123** [comment]
Scripts get converted to `console_scripts` entry points, [plugins](https://poetry.eustace.io/docs/pyproject/#plugins) would allow for arbitrary entry points.

**Comment by cjw296** [comment]
@astronouth7303 - here's something that might help you:
https://github.com/sdispater/poetry/issues/658
If it does, would you mind closing this issue and tracking it there?

**Comment by astronouth7303** [comment]
Oh! Sorry, it wasn't super clear that "plugins" were package declarations and not hooks for poetry.

**Comment by cjw296** [comment]
No worries, it's definitely not clear, but when that linked issues gets resolved, we'll have better docs :-)

**Comment by tedmiston** [comment]
I had the same misconception as @astronouth7303 and ended up at this issue [searching][1] the Poetry docs and then repo for standard setuptools terms like `console_scripts`.  It does not appear to be mentioned anywhere in them today.

[I did quite a bit of wondering about how to generate my `setup.py` with Poetry until discovering it was being done automatically.  I feel like this may be worth calling out explicitly for users coming from other packaging tools where we are used to explicitly writing or explicitly generating the setup.py etc.]

It may also be helpful to add a mention of `console_scripts` to the [scripts section][2] of the `pyproject.toml` page in the docs.  The current example on the page is confusing because it refers to Poetry itself rather than e.g., the package one is developing.

In my opinion it would be a lot clearer if this example:

```
[tool.poetry.scripts]
poetry = 'poetry:console.run'
```

Was changed to one with more familiar, relatable vocabulary such as:

```
[tool.poetry.scripts]
my-cli = 'my_package.my_module:my_function'
```

Or at least if explanation could be added to discuss how this is used behind the scenes.

[1]: https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Fpoetry.eustace.io%2Fdocs%2F%20%22console_scripts%22
[2]: https://poetry.eustace.io/docs/pyproject/#scripts

**Comment by corydodt** [comment]
> It may also be helpful to add a mention of `console_scripts` to the [scripts section](https://poetry.eustace.io/docs/pyproject/#scripts) of the `pyproject.toml` page in the docs. The current example on the page is confusing because it refers to Poetry itself rather than e.g., the package one is developing.

To piggyback, I think there would be a huge amount of value in having some "poetry for setup.py users" page that just described how you translate one concept into the other, for a variety of common concepts.

**Comment by robsonpeixoto** [comment]
How can I configure a entry_point like that https://airflow.apache.org/docs/apache-airflow/stable/plugins.html#plugins-as-python-packages using poetry?

```py
from setuptools import setup

setup(
    name="my-package",
    ...
    entry_points = {
        'airflow.plugins': [
            'my_plugin = my_package.my_plugin:MyAirflowPlugin'
        ]
    }
)
```

**Comment by abn** [comment]
@robsonpeixoto you might be looking for https://python-poetry.org/docs/pyproject/#plugins. Also; since this issue is closed might be better start a discussion and/or raise a new issue.

**Comment by shaunc** [comment]
@abn I think what this issue was referring to is [entry points according to PEP 621](https://www.python.org/dev/peps/pep-0621/#entry-points). It isn't about poetry-specific plugins, but ones that use -- e.g. -- [pluggy](https://pluggy.readthedocs.io/en/stable/) Should I open another issue for this?

**Comment by gutomaia** [comment]
> How can I configure a entry_point like that https://airflow.apache.org/docs/apache-airflow/stable/plugins.html#plugins-as-python-packages using poetry?
> 
> ```python
> from setuptools import setup
> 
> setup(
>     name="my-package",
>     ...
>     entry_points = {
>         'airflow.plugins': [
>             'my_plugin = my_package.my_plugin:MyAirflowPlugin'
>         ]
>     }
> )
> ```

Fala Robinho!

Did you managed to use poetry with entrypoints?

**Comment by robsonpeixoto** [comment]
Diga Guto (@gutomaia)!
The @abn tip worked for me.
