### ISSUE TITLE
Get Github to recognize dependencies in pyproject.toml

### ISSUE THREAD

**Issue by dimaqq** [sdispater/poetry#962]
We've moved to `poetry` and lost automatic notifications about outdated dependencies:

https://github.com/HENNGE/aiodynamo/network/dependencies

I understand that's tricky to accomplish, perhaps someone can help?

**Comment by pmav99** [comment]
@dimaqq you should open send an email to support@github.com asking them to add support for poetry.lock too

**Comment by hangtwenty** [comment]
Agreed that this wound be wonderful

Hopefully GitHub can handle it since it is really their level of concern

In the meantime a workaround would be to export a `requirements.txt` to a folder in your repo just for this. You'd just need to document/inform teammates not to depend on that artifact directly

**Comment by psincraian** [comment]
Maybe you can try dependabot or others services meanwhile: https://dependabot.com/blog/announcing-poetry-support/

**Comment by dimaqq** [comment]
@pmav99 I'll do that; perhaps it helps if they get several requests on on the subject :)

@hangtwenty Indeed; There's a precedent too, apparently `Pipfile.lock` is already understood: https://github.com/klee94/pipenv-with-pipfile-dot-lock/network/dependencies

@psincraian Thanks for the tip :)

**Comment by sdispater** [comment]
Unfortunately it's not up to us to add this feature but it's on Github's end
