### ISSUE TITLE
Add poetry to Heroku's Python buildpack

### ISSUE THREAD

**Issue by golyalpha** [sdispater/poetry#971]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

As things are currently, I'd really love to use poetry for *all* my projects, unfortunately, I can't.  
I have about 5 Python projects, of which I am the sole author, running on Heroku, as of right now, most of them are using Pipenv or bare pip for dependencies, the reason being simple: The official Python buildpack doesn't support poetry, and I couldn't find one that does.

I know that this is more of an issue with the Python buildpack for Heroku, than with Poetry itself, but if we don't take steps towards getting it supported, who else should? That is why am I posting an issue here.

I have a fork of the buildpack, where I'm trying to add that support [here](https://github.com/golyalpha/heroku-buildpack-python), but I lack the means necessary to test it, so I encourage you to test it, and help me out with that in general.

**Comment by AndreGuerra123** [comment]
I've done a [pull request](https://github.com/heroku/heroku-buildpack-python/pull/807) to Heroku's Python buildpack with testing and all. You could find my fork [here](https://github.com/AndreGuerra123/heroku-buildpack-python) aswell. 

I've submitted this pull request 20 days ago with no feedback so far. It need some obvious adjustments.
[ ] Squash my lame commits.
[ ] Lint my bash scripts
[ ] Run TravisCI properly

I really do not know what's happening with their CI (probably needs some special authentication, or the hatchet API keys expired, since the main admin is having issues on submitting their own pull requests).

However, I used docker and  `make test` and all old and new tests passed.

There is always room for improvement and I hope you succeed where I failed, 

Cheers

PS: Your pull request and issues should be directed to that package. I think they will close it here.

**Comment by golyalpha** [comment]
@AndreGuerra123 Have you suceeded in using your buildpack on a heroku dyno?

**Comment by golyalpha** [comment]
@AndreGuerra123 Have you suceeded in using your buildpack on a heroku dyno?

**Comment by golyalpha** [comment]
@AndreGuerra123 You apparently have a typo in the pull request's code.

@cjw296 Alright, will do, since it seems integration is underway.

**Comment by zyv** [comment]
FYI we have written our own buildpack to plug it on top of the official Python buildpack, because no-one knows if and when Heroku will officially support Poetry:

https://github.com/moneymeets/python-poetry-buildpack

**Comment by golyalpha** [comment]
Yeah, I just ended up using the container runtime and Dockerfile+heroku.yml instead of Heroku's buildpacks. Ended up making our migration away from Heroku about 10x more painless in the long run.
