### ISSUE TITLE
Check for security vulnerabilities

### ISSUE THREAD

**Issue by Euphorbium** [sdispater/poetry#994]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request
`pipenv check` scans for known security vulnerabilities in the dependancies. Poetry check does not seem to do that. Poetry should have a way to check for known security vulnerabilities.

**Comment by hangtwenty** [comment]
It’s a great idea for you to check for security vulnerabilities. 

It’s out of scope though. 

It’s not great for Poetry to assume what tool you want to use or your threshold for “OK.” There’s an argument to be made that building that in like that, without the user thinking about it, can provide a _false_ sense of security since it is only one kind of check.

**Comment by hangtwenty** [comment]
OP, you may be interested to join the discussion of ways to streamline dev tasks with Poetry; security linting for dependencies would be an example of a great task to have examples for.

https://github.com/sdispater/poetry/issues/241

**Comment by Euphorbium** [comment]
https://github.com/pyupio/safety completely solves my needs. No need to do this in poetry.

**Comment by MisterGlass** [comment]
If anyone is looking to do this, you can use this bash one liner to run a check:
`poetry export --without-hashes -f requirements.txt | safety check --full-report --stdin`
